<?php

namespace Database\Seeders;

use App\Models\Carousel;
use App\Models\Size;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarouselV2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Carousel::query()->update(['visible' => 0]);

        $carousels = [
            //Drumeo
            [
                'brand_id' => 1,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/EloyCasagrande-Logo-1683062774.svg',
                'subtitle' => '',
                'title' => 'Eloy Casagrande Live',
                'name' => 'Eloy Casagrande Live',
                'description' => 'Join us LIVE in the Drumeo studio with Eloy:<br>
May 8th (2:30PM PT) - The Drum Department<br>
May 10th (3:00PM PT) - Drumeo Live Lesson',
                'primary_cta_text' => 'More Info',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/drumeo/forums/drumeo-edge-discussion/9/live-events-with-eloy-casagrande-sepulturas-drummer/14907?sortby_val=-published_on',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Eloy_Desktop-1683062681.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Eloy_Tablet-1683062729.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Eloy_Mobile-1683062751.jpg',
                'display_order' => 1,
                'start_date' => '05/01/2023, 8:00',
                'end_date' => '05/10/2023, 23:59',
            ],
            [
                'brand_id' => 1,
                'logo' => '',
                'subtitle' => '',
                'title' => '6 Days Left. Refer & Win $100',
                'name' => 'Win a $100 Amazon Gift Card',
                'description' => 'Love your friends like you love music. Refer a friend to Drumeo and you could win a $100 Amazon gift card. The contest ends on May 8, 2023.',
                'primary_cta_text' => 'ENTER THE CONTEST',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/drumeo/referral/invite-a-friend',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Desktop-1683042267.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Tablet-1683042303.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Mobile-1683042328.jpg',
                'display_order' => 2,
                'desc_color' => 'black',
                'start_date' => '04/06/2023, 11:22',
                'end_date' => '05/08/2023, 23:22',
            ],
            [
                'brand_id' => 1,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Logo_Logo-1683138509.svg',
                'subtitle' => 'MAY',
                'title' => 'NEW SONG RELEASES',
                'name' => 'NEW SONG RELEASES',
                'description' => 'New Songs releasing every Thursday in April!',
                'primary_cta_text' => 'GO TO SONGS',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/drumeo/songs',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Desktop-1683138448.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Tablet-1683138464.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Mobile-1683138474.jpg',
                'display_order' => 3,
                'desc_color' => 'black',
                'start_date' => '05/01/2023, 1:10',
                'end_date' => '05/31/2023, 12:50',
            ],
            [
                'brand_id' => 1,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Logo copy-1683069327.svg',
                'subtitle' => '',
                'title' => 'Drum Department',
                'name' => 'Drum Department',
                'description' => 'Join us every Monday for a new episode!',
                'primary_cta_text' => 'Next Episode',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/drumeo/live',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Desktop copy-1683067849.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Tablet copy-1683068162.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Mobile copy-1683068245.jpg',
                'display_order' => 4,
                'start_date' => '05/01/2023, 1:00',
                'end_date' => '',
            ],
            //Pianote
            [
                'brand_id' => 2,
                'logo' => '',
                'subtitle' => '',
                'title' => '6 Days Left. Refer & Win $100',
                'name' => 'Win a $100 Amazon Gift Card',
                'description' => 'Love your friends like you love music. Refer a friend to Drumeo and you could win a $100 Amazon gift card. The contest ends on May 8, 2023.',
                'primary_cta_text' => 'ENTER THE CONTEST',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/pianote/referral/invite-a-friend',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Desktop-1683042267.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Tablet-1683042303.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Mobile-1683042328.jpg',
                'display_order' => 1,
                'desc_color' => 'black',
                'start_date' => '04/06/2023, 11:22',
                'end_date' => '05/08/2023, 23:22',
            ],
            [
                'brand_id' => 2,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Logo_Logo-1683138509.svg',
                'subtitle' => '',
                'title' => 'Weekly Song Release!',
                'name' => 'Weekly Song Release!',
                'description' => '',
                'primary_cta_text' => 'GO TO SONGS',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/pianote/songs',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Desktop-1683141303.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Tablet-1683141447.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Mobile-1683141482.jpg',
                'display_order' => 2,
                'desc_color' => 'black',
                'start_date' => '05/01/2023, 1:00',
                'end_date' => '',
            ],
            //Guitareo
            [
                'brand_id' => 3,
                'logo' => '',
                'subtitle' => '',
                'title' => '6 Days Left. Refer & Win $100',
                'name' => 'Win a $100 Amazon Gift Card',
                'description' => 'Love your friends like you love music. Refer a friend to Drumeo and you could win a $100 Amazon gift card. The contest ends on May 8, 2023.',
                'primary_cta_text' => 'ENTER THE CONTEST',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/guitareo/referral/invite-a-friend',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Desktop-1683042267.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Tablet-1683042303.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Mobile-1683042328.jpg',
                'display_order' => 1,
                'desc_color' => 'black',
                'start_date' => '04/06/2023, 11:22',
                'end_date' => '05/08/2023, 23:22',
            ],
            [
                'brand_id' => 3,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Logo_Logo-1683138509.svg',
                'subtitle' => '',
                'title' => 'Weekly Song Release!',
                'name' => 'Weekly Song Release!',
                'description' => "Guitar-less versions now available for all new releases. This week's release includes beautiful staples like Sweet Child O' Mine, Highway Star, Folsom Prison Blues and Master Of Puppets!",
                'primary_cta_text' => 'Click here to see the list of all 15 releases.',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/guitareo/forums/guitareo-songs-discussions/9/april-27-happy-birthday-ace/2953',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Desktop-1683139609.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template-tablet-1683139678.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Mobile-1683139654.jpg',
                'display_order' => 2,
                'desc_color' => 'black',
                'start_date' => '05/01/2023, 1:00',
                'end_date' => '',
            ],
            //Singeo
            [
                'brand_id' => 4,
                'logo' => '',
                'subtitle' => '',
                'title' => 'Win a $100 Amazon Gift Card',
                'name' => '6 Days Left. Refer & Win $100',
                'description' => 'Love your friends like you love music. Refer a friend to Drumeo and you could win a $100 Amazon gift card. The contest ends on May 8, 2023.',
                'primary_cta_text' => 'ENTER THE CONTEST',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/singeo/referral/invite-a-friend',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Desktop-1683042267.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Tablet-1683042303.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-AmazonGiftCard_Mobile-1683042328.jpg',
                'display_order' => 1,
                'desc_color' => 'black',
                'start_date' => '04/06/2023, 11:22',
                'end_date' => '05/08/2023, 23:22',
            ],
            [
                'brand_id' => 4,
                'logo' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Logo_Logo-1683138509.svg',
                'subtitle' => '',
                'title' => 'Weekly Song Release!',
                'name' => 'Weekly Song Release!',
                'description' => 'Songs that are automatically synced to sheet music with audio tracks. You can adjust the speed, create practice loops, and play with or without the metronome. Check out our library and choose your favorite now!',
                'primary_cta_text' => 'GO TO SONGS',
                'primary_cta_text_alt' => '',
                'primary_cta_url' => 'https://www.musora.com/singeo/songs',
                'primary_cta_url_alt' => '',
                'secondary_cta_text' => '',
                'secondary_cta_url' => '',
                'desktop_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_desktop-1683141093.jpg',
                'tablet_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Tablet-1683141208.jpg',
                'mobile_img' => 'https://d1923uyy6spedc.cloudfront.net/NewBannerFormat-Template_Mobile-1683141108.jpg',
                'display_order' => 2,
                'desc_color' => 'black',
                'start_date' => '05/01/2023, 1:00',
                'end_date' => '',
            ],
        ];

        foreach($carousels as $carousel){
            Carousel::create([
                                 'brand_id' => $carousel['brand_id'],
                                 'logo' => $carousel['logo'],
                                 'subtitle' => $carousel['subtitle'],
                                 'title' => $carousel['title'],
                                 'name' => $carousel['name'],
                                 'description' => $carousel['description'],
                                 'desc_color' => !empty($carousel['desc_color']) ? $carousel['desc_color'] : null,
                                 'start_date' => !empty($carousel['start_date']) ? $carousel['start_date'] : null,
                                 'end_date' => !empty($carousel['end_date']) ? $carousel['end_date'] : null,
                                 'primary_cta_text' => $carousel['primary_cta_text'],
                                 'primary_cta_text_alt' => $carousel['primary_cta_text_alt'],
                                 'secondary_cta_text' => $carousel['secondary_cta_text'],
                                 'primary_cta_url' => $carousel['primary_cta_url'],
                                 'primary_cta_url_alt' => $carousel['primary_cta_url_alt'],
                                 'secondary_cta_url' => $carousel['secondary_cta_url'],
                                 'desktop_img' => $carousel['desktop_img'],
                                 'tablet_img' => $carousel['tablet_img'],
                                 'mobile_img' => $carousel['mobile_img'],
                                 'display_order' => $carousel['display_order'],
                                 'is_featured' => 0
                             ]);
        }
    }
}
