<?php /** @noinspection ALL */
// Generated by Avo VERSION 116.206.0. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.

class Avo
{
    private static $__VERBOSE__ = TRUE;
    private static $__STRICT__ = TRUE;
    private static $__AVO_ENV__ = NULL;

    /** @var \Psr\Log\LoggerInterface */
    private static $__LOGGER__ = NULL;

    // assertion prelude
    private static function _avo_assert_int($property_id, $property_name, $num)
    {
        if (!is_int($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedIntType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type int but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_long($property_id, $property_name, $num)
    {
        if (!is_long($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedLongType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type long but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_float($property_id, $property_name, $num)
    {
        if (!is_float($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedFloatType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type float but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_object($property_id, $property_name, $value)
    {
        if (!is_array($value) || array_keys($value) === range(0, count($value) - 1)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedObjectType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type associative array but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_string($property_id, $property_name, $value)
    {
        if (!is_string($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedStringType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type string but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_bool($property_id, $property_name, $value)
    {
        if (!is_bool($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedBoolType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type boolean but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_list($property_id, $property_name, $list)
    {
        if (!is_array($list)) {
            $actual_type = gettype($list);
            return [['tag' => 'expectedList', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type list but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_min($property_id, $property_name, $min, $value)
    {
        if ($value < $min) {
            return [['tag' => 'expectedMin', 'propertyId' => $property_id, 'message' => "{$property_name} has a minimum value of {$min} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_max($property_id, $property_name, $max, $value)
    {
        if ($value > $max) {
            return [['tag' => 'expectedMax', 'propertyId' => $property_id, 'message' => "{$property_name} has a maximum value of {$max} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }



    private static $samplingRate = 1.0;

    private static function _invoke($event_id, $hash, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'uv3TOorcWMa4CtfVX8wR',
                        'br' => 'master',
                        'en' => self::$__AVO_ENV__,
                        'ev' => $event_id,
                        'ha' => $hash,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                        'or' => 'event',
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, TRUE);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }

    private static function _invoke_meta($type, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'uv3TOorcWMa4CtfVX8wR',
                        'br' => 'master',
                        'en' => self::$__AVO_ENV__,
                        'ty' => $type,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, TRUE);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }


     // instance for rudder_stack destination
     private static $rudder_stackDestination = NULL;

     public static function init_avo($options)
     {
         self::$__STRICT__ = isset($options['strict']) ? $options['strict'] : TRUE;
         self::$__VERBOSE__ = isset($options['verbose']) ? $options['verbose'] : TRUE;
         self::$__AVO_ENV__ = $options['env'];
         self::$__LOGGER__ = $options['logger'];

         self::$rudder_stackDestination = $options['rudder_stack_instance'];
         if (method_exists(self::$rudder_stackDestination, 'make')) {
             if (self::$__AVO_ENV__ === 'prod') {
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             } else if (self::$__AVO_ENV__ === 'dev') {
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             } else {
                 self::$__LOGGER__->error("[avo] No staging key is set for RudderStack. Head to destination settings in Avo to set a staging key");
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             }
         }
         if (self::$__AVO_ENV__ !== 'prod') {
             // debug console in Avo
             self::_invoke_meta('init', []);
         }
     }

     private static function _assert_brand($brand, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('5mOEXJ648', isset($label_) ? 'brand' . ':' . $label_ : 'brand', $brand));
         if ($brand !== 'drumeo' &&
             $brand !== 'guitareo' &&
             $brand !== 'musora' &&
             $brand !== 'recordeo' &&
             $brand !== 'singeo' &&
             $brand !== 'pianote') {
             array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '5mOEXJ648', 'message' => (isset($label_) ? 'brand' . ': ' . $label_ : 'brand') . " should match one of the following values [ drumeo | guitareo | musora | recordeo | singeo | pianote ] but you provided the value {$brand}"]);
         }
         return $messages;
     }

     private static function _assert_gear_list($gear_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('Fx30ZyaXN', 'gear_list', $gear_list));
         if (is_array($gear_list)) {
             foreach($gear_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_genre_list($genre_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('N5hB7Rf5K', 'genre_list', $genre_list));
         if (is_array($genre_list)) {
             foreach($genre_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_user_id_($user_id_, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('avo-enriched-server-user-id', isset($label_) ? 'User Id' . ':' . $label_ : 'User Id', $user_id_));
         return $messages;
     }

     private static function _assert_topic_list($topic_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('bjLJ9Wifx', 'topic_list', $topic_list));
         if (is_array($topic_list)) {
             foreach($topic_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_is_skipped($is_skipped, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_bool('hizp-XQNB', isset($label_) ? 'is_skipped' . ':' . $label_ : 'is_skipped', $is_skipped));
         return $messages;
     }

     private static function _assert_experience_level($experience_level, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('kJBXPS-Rv', isset($label_) ? 'experience_level' . ':' . $label_ : 'experience_level', $experience_level));
         return $messages;
     }

     private static function _assert_musora_user_id($musora_user_id, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_int('oj0he-89m', isset($label_) ? 'musora_user_id' . ':' . $label_ : 'musora_user_id', $musora_user_id));
         return $messages;
     }

     public static function onboarding_started($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             // debug console in Avo
             self::_invoke('FeaHCzH-x', '1594c8d0b8ba2b698d22501ebddd40f38344ea75ed7dd210b5ee23e9203e72cf', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Started': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Started', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Started', [
         'musora_user_id' => $properties['musora_user_id'],
         ]);
     }

     public static function account_created($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             // debug console in Avo
             self::_invoke('P07BEO3Z8', 'cf5375f5172dc8ca3c1176b314b4c1262754699db7db1bd9be9214493fb5faf0', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Account Created': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Account Created', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Account Created', [
         'musora_user_id' => $properties['musora_user_id'],
         ]);
     }

     public static function instrument_onboarding_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             // debug console in Avo
             self::_invoke('m-5bPn9dHs', '092ed3bada026af2ae6735011aa04d29b240db5eb05d6d1f633f9fa0f8a361a0', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Instrument Onboarding Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Instrument Onboarding Step Completed', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             'brand' => $properties['brand'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Instrument Onboarding Step Completed', [
         'musora_user_id' => $properties['musora_user_id'],
         'brand' => $properties['brand'],
         ]);
     }

     public static function gear_onboarding_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
             $messages = array_merge($messages, self::_assert_gear_list($properties['gear_list']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             // debug console in Avo
             self::_invoke('aPa8PWuKjC', 'c4d7ed93f7fa3ab51bf72dfd388cf2a94aa77fc4ce5254da628add3fbedf077c', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Gear Onboarding Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Gear Onboarding Step Completed', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             'is_skipped' => $properties['is_skipped'],
             'gear_list' => $properties['gear_list'],
             'brand' => $properties['brand'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Gear Onboarding Step Completed', [
         'musora_user_id' => $properties['musora_user_id'],
         'is_skipped' => $properties['is_skipped'],
         'gear_list' => $properties['gear_list'],
         'brand' => $properties['brand'],
         ]);
     }

     public static function experience_onboarding_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
             $messages = array_merge($messages, self::_assert_experience_level($properties['experience_level']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             // debug console in Avo
             self::_invoke('QGsppNv0OJ', 'e28a37e9043000a7527bb5c816e9dd98004412c56e944fdd55ed8e0a630e8e4e', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Experience Onboarding Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Experience Onboarding Step Completed', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             'is_skipped' => $properties['is_skipped'],
             'experience_level' => $properties['experience_level'],
             'brand' => $properties['brand'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Experience Onboarding Step Completed', [
         'musora_user_id' => $properties['musora_user_id'],
         'is_skipped' => $properties['is_skipped'],
         'experience_level' => $properties['experience_level'],
         'brand' => $properties['brand'],
         ]);
     }

     public static function genres_onboarding_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
             $messages = array_merge($messages, self::_assert_genre_list($properties['genre_list']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             // debug console in Avo
             self::_invoke('t9Z83FSnYD', '00375787792408bca5ef7513b9c5983a5a498bc72a4592c19e7e8ea47af3116f', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Genres Onboarding Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Genres Onboarding Step Completed', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             'is_skipped' => $properties['is_skipped'],
             'genre_list' => $properties['genre_list'],
             'brand' => $properties['brand'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Genres Onboarding Step Completed', [
         'musora_user_id' => $properties['musora_user_id'],
         'is_skipped' => $properties['is_skipped'],
         'genre_list' => $properties['genre_list'],
         'brand' => $properties['brand'],
         ]);
     }

     public static function topics_onboarding_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_musora_user_id($properties['musora_user_id']));
             $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_topic_list($properties['topic_list']));
             // debug console in Avo
             self::_invoke('ynS7ECZHra', '8a4ba66ffd3069bd497f20b392bd514e54f3de76db21566842c96778e5356290', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Topics Onboarding Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Topics Onboarding Step Completed', Event props: ". print_r(array_filter([
             'musora_user_id' => $properties['musora_user_id'],
             'is_skipped' => $properties['is_skipped'],
             'brand' => $properties['brand'],
             'topic_list' => $properties['topic_list'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Topics Onboarding Step Completed', [
         'musora_user_id' => $properties['musora_user_id'],
         'is_skipped' => $properties['is_skipped'],
         'brand' => $properties['brand'],
         'topic_list' => $properties['topic_list'],
         ]);
     }

     public static function test($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             // debug console in Avo
             self::_invoke('v9hBUbBzq-', 'a1223eb955c2e5619c2408f2a102654699921143fa863e268782d9349f47919c', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Test': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Test', Event props: ". print_r(array_filter([
             'brand' => $properties['brand'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Test', [
         'brand' => $properties['brand'],
         ]);
     }

}
if (!function_exists('json_encode')) {
    throw new \Exception('Avo needs the JSON PHP extension.');
}
// AVOMODULEMAP:"Avo"
// AVOEVENTMAP:["onboarding_started","account_created","instrument_onboarding_step_completed","gear_onboarding_step_completed","experience_onboarding_step_completed","genres_onboarding_step_completed","topics_onboarding_step_completed","test"]
