<?php

/** @noinspection ALL */
// Generated by Avo VERSION 135.0.0. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.

class Avo
{
    private static $__VERBOSE__ = true;
    private static $__STRICT__ = true;
    private static $__AVO_ENV__ = null;

    /** @var \Psr\Log\LoggerInterface */
    private static $__LOGGER__ = null;

    // assertion prelude
    private static function _avo_assert_int($property_id, $property_name, $num)
    {
        if (!is_int($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedIntType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type int but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_long($property_id, $property_name, $num)
    {
        if (!is_long($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedLongType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type long but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_float($property_id, $property_name, $num)
    {
        if (!is_float($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedFloatType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type float but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_object($property_id, $property_name, $value)
    {
        if (!is_array($value) || array_keys($value) === range(0, count($value) - 1)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedObjectType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type associative array but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_string($property_id, $property_name, $value)
    {
        if (!is_string($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedStringType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type string but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_bool($property_id, $property_name, $value)
    {
        if (!is_bool($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedBoolType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type boolean but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_list($property_id, $property_name, $list)
    {
        if (!is_array($list)) {
            $actual_type = gettype($list);
            return [['tag' => 'expectedList', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type list but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_min($property_id, $property_name, $min, $value)
    {
        if ($value < $min) {
            return [['tag' => 'expectedMin', 'propertyId' => $property_id, 'message' => "{$property_name} has a minimum value of {$min} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_max($property_id, $property_name, $max, $value)
    {
        if ($value > $max) {
            return [['tag' => 'expectedMax', 'propertyId' => $property_id, 'message' => "{$property_name} has a maximum value of {$max} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }



    private static $samplingRate = 1.0;

    private static function _invoke($event_id, $hash, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'Y3VFudIkpNVS0yyLD1Mv',
                        'br' => 'master',
                        'en' => self::$__AVO_ENV__,
                        'ev' => $event_id,
                        'ha' => $hash,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function ($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                        'or' => 'event',
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, true);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }

    private static function _invoke_meta($type, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'Y3VFudIkpNVS0yyLD1Mv',
                        'br' => 'master',
                        'en' => self::$__AVO_ENV__,
                        'ty' => $type,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function ($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, true);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }


    // instance for rudder_stack destination
    private static $rudder_stackDestination = null;

    public static function init_avo($options)
    {
        self::$__STRICT__ = isset($options['strict']) ? $options['strict'] : true;
        self::$__VERBOSE__ = isset($options['verbose']) ? $options['verbose'] : true;
        self::$__AVO_ENV__ = $options['env'];
        self::$__LOGGER__ = $options['logger'];

        self::$rudder_stackDestination = $options['rudder_stack_instance'];
        if (method_exists(self::$rudder_stackDestination, 'make')) {
            if (self::$__AVO_ENV__ === 'prod') {
                self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
            } elseif (self::$__AVO_ENV__ === 'dev') {
                self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
            } else {
                self::$__LOGGER__->error("[avo] No staging key is set for RudderStack. Head to destination settings in Avo to set a staging key");
                self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
            }
        }
        if (self::$__AVO_ENV__ !== 'prod') {
            // debug console in Avo
            self::_invoke_meta('init', []);
        }
    }

    private static function _assert_filters($filters, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('0W4owU4RO', 'filters', $filters));
        if (is_array($filters)) {
            foreach($filters as $key => $value) {
                $messages = array_merge($messages, self::_avo_assert_object('0W4owU4RO', 'item at index ' . $key . ' in filters', $value));
                $messages = array_merge($messages, self::_assert_filter_category($value['filter_category'], 'item at index ' . $key . ' in filters'));
                $messages = array_merge($messages, self::_assert_filter_tag($value['filter_tag'], 'item at index ' . $key . ' in filters'));
            }
        }
        return $messages;
    }

    private static function _assert_revenue($revenue, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('2aO3BixNf', isset($label_) ? 'revenue' . ':' . $label_ : 'revenue', $revenue));
        return $messages;
    }

    private static function _assert_filter_group($filter_group, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('2ntYcoVYq', isset($label_) ? 'filter_group' . ':' . $label_ : 'filter_group', $filter_group));
        return $messages;
    }

    private static function _assert_step_skipped_optional($step_skipped, $label_ = null)
    {
        $messages = [];
        if (isset($step_skipped)) {
            $messages = array_merge($messages, self::_avo_assert_string('3VO48nTzt-', isset($label_) ? 'step_skipped' . ':' . $label_ : 'step_skipped', $step_skipped));
            if ($step_skipped !== 'gear' &&
                $step_skipped !== 'experience' &&
                $step_skipped !== 'genres' &&
                $step_skipped !== 'topics' &&
                $step_skipped !== 'goals') {
                array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '3VO48nTzt-', 'message' => (isset($label_) ? 'step_skipped' . ': ' . $label_ : 'step_skipped') . " should match one of the following values [ gear | experience | genres | topics | goals ] but you provided the value {$step_skipped}"]);
            }
        }
        return $messages;
    }

    private static function _assert_brand($brand, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('5mOEXJ648', isset($label_) ? 'brand' . ':' . $label_ : 'brand', $brand));
        if ($brand !== 'drumeo' &&
            $brand !== 'guitareo' &&
            $brand !== 'musora' &&
            $brand !== 'recordeo' &&
            $brand !== 'singeo' &&
            $brand !== 'pianote') {
            array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '5mOEXJ648', 'message' => (isset($label_) ? 'brand' . ': ' . $label_ : 'brand') . " should match one of the following values [ drumeo | guitareo | musora | recordeo | singeo | pianote ] but you provided the value {$brand}"]);
        }
        return $messages;
    }

    private static function _assert_homepage_section($homepage_section, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('7lHiW6ZgW', isset($label_) ? 'homepage_section' . ':' . $label_ : 'homepage_section', $homepage_section));
        if ($homepage_section !== 'recommended' &&
            $homepage_section !== 'new' &&
            $homepage_section !== 'playlists' &&
            $homepage_section !== 'workouts' &&
            $homepage_section !== 'continue' &&
            $homepage_section !== 'banner' &&
            $homepage_section !== 'upcoming-events' &&
            $homepage_section !== 'live') {
            array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '7lHiW6ZgW', 'message' => (isset($label_) ? 'homepage_section' . ': ' . $label_ : 'homepage_section') . " should match one of the following values [ recommended | new | playlists | workouts | continue | banner | upcoming-events | live ] but you provided the value {$homepage_section}"]);
        }
        return $messages;
    }

    private static function _assert_currency($currency, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('CYZcIR8zU', isset($label_) ? 'currency' . ':' . $label_ : 'currency', $currency));
        return $messages;
    }

    private static function _assert_shipping($shipping, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('DgJwW8gJZ', isset($label_) ? 'shipping' . ':' . $label_ : 'shipping', $shipping));
        return $messages;
    }

    private static function _assert_content_id_optional($content_id, $label_ = null)
    {
        $messages = [];
        if (isset($content_id)) {
            $messages = array_merge($messages, self::_avo_assert_int('EYlcIbuNn', isset($label_) ? 'content_id' . ':' . $label_ : 'content_id', $content_id));
        }
        return $messages;
    }

    private static function _assert_products($products, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('Ek1UWureB', 'products', $products));
        if (is_array($products)) {
            foreach($products as $key => $value) {
                $messages = array_merge($messages, self::_avo_assert_object('Ek1UWureB', 'item at index ' . $key . ' in products', $value));
                $messages = array_merge($messages, self::_assert_product_id($value['product_id'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_product_name($value['product_name'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_brand($value['brand'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_price($value['price'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_quantity($value['quantity'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_variant_id($value['variant_id'], 'item at index ' . $key . ' in products'));
                $messages = array_merge($messages, self::_assert_sku($value['sku'], 'item at index ' . $key . ' in products'));
            }
        }
        return $messages;
    }

    private static function _assert_products_optional($products, $label_ = null)
    {
        $messages = [];
        if (isset($products)) {
            $messages = array_merge($messages, self::_avo_assert_list('Ek1UWureB', 'products', $products));
            if (is_array($products)) {
                foreach($products as $key => $value) {
                    $messages = array_merge($messages, self::_avo_assert_object('Ek1UWureB', 'item at index ' . $key . ' in products', $value));
                    $messages = array_merge($messages, self::_assert_product_id($value['product_id'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_product_name($value['product_name'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_brand($value['brand'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_price($value['price'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_quantity($value['quantity'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_variant_id($value['variant_id'], 'item at index ' . $key . ' in products'));
                    $messages = array_merge($messages, self::_assert_sku($value['sku'], 'item at index ' . $key . ' in products'));
                }
            }
        }
        return $messages;
    }

    private static function _assert_gear_list($gear_list, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('Fx30ZyaXN', 'gear_list', $gear_list));
        if (is_array($gear_list)) {
            foreach($gear_list as $key => $value) {
            }
        }
        return $messages;
    }

    private static function _assert_total($total, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('GZt8F8eCw', isset($label_) ? 'total' . ':' . $label_ : 'total', $total));
        return $messages;
    }

    private static function _assert_tax($tax, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('IUkAUDkH_', isset($label_) ? 'tax' . ':' . $label_ : 'tax', $tax));
        return $messages;
    }

    private static function _assert_refund_amount($refund_amount, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('Jfp12lDt5', isset($label_) ? 'refund_amount' . ':' . $label_ : 'refund_amount', $refund_amount));
        return $messages;
    }

    private static function _assert_quantity($quantity, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('KrvuMuah_-', isset($label_) ? 'quantity' . ':' . $label_ : 'quantity', $quantity));
        return $messages;
    }

    private static function _assert_sku($sku, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('LiJVuyrhU', isset($label_) ? 'sku' . ':' . $label_ : 'sku', $sku));
        return $messages;
    }

    private static function _assert_account_created_at($account_created_at, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('MT5OF-ifv', isset($label_) ? 'account_created_at' . ':' . $label_ : 'account_created_at', $account_created_at));
        return $messages;
    }

    private static function _assert_genre_list($genre_list, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('N5hB7Rf5K', 'genre_list', $genre_list));
        if (is_array($genre_list)) {
            foreach($genre_list as $key => $value) {
            }
        }
        return $messages;
    }

    private static function _assert_order_id($order_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('PHSY4a14M', isset($label_) ? 'order_id' . ':' . $label_ : 'order_id', $order_id));
        return $messages;
    }

    private static function _assert_variant_id($variant_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('PVUTyuD7q', isset($label_) ? 'variant_id' . ':' . $label_ : 'variant_id', $variant_id));
        return $messages;
    }

    private static function _assert_product_name($product_name, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('RKP62a3Tg', isset($label_) ? 'product_name' . ':' . $label_ : 'product_name', $product_name));
        return $messages;
    }

    private static function _assert_branch_name($branch_name, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('SnDB1flYg', isset($label_) ? 'branch_name' . ':' . $label_ : 'branch_name', $branch_name));
        return $messages;
    }

    private static function _assert_filter_category($filter_category, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('YzUmJzSAj', isset($label_) ? 'filter_category' . ':' . $label_ : 'filter_category', $filter_category));
        return $messages;
    }

    private static function _assert_is_skipped($is_skipped, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_bool('ZSKmyfbiL-', isset($label_) ? 'is_skipped' . ':' . $label_ : 'is_skipped', $is_skipped));
        return $messages;
    }

    private static function _assert_goals_list($goals_list, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('a97p4BAJd', 'goals_list', $goals_list));
        if (is_array($goals_list)) {
            foreach($goals_list as $key => $value) {
            }
        }
        return $messages;
    }

    private static function _assert_sorting_type($sorting_type, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('aPHDsEZbW', isset($label_) ? 'sorting_type' . ':' . $label_ : 'sorting_type', $sorting_type));
        return $messages;
    }

    private static function _assert_user_id_($user_id_, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('avo-enriched-server-user-id', isset($label_) ? 'User Id' . ':' . $label_ : 'User Id', $user_id_));
        return $messages;
    }

    private static function _assert_topic_list($topic_list, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_list('bjLJ9Wifx', 'topic_list', $topic_list));
        if (is_array($topic_list)) {
            foreach($topic_list as $key => $value) {
            }
        }
        return $messages;
    }

    private static function _assert_subtotal($subtotal, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('c9Wexw8g2', isset($label_) ? 'subtotal' . ':' . $label_ : 'subtotal', $subtotal));
        return $messages;
    }

    private static function _assert_branch_id($branch_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('ci2gNrVaV', isset($label_) ? 'branch_id' . ':' . $label_ : 'branch_id', $branch_id));
        return $messages;
    }

    private static function _assert_payment_source($payment_source, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('dobL078Zl', isset($label_) ? 'payment_source' . ':' . $label_ : 'payment_source', $payment_source));
        if ($payment_source !== 'web' &&
            $payment_source !== 'apple' &&
            $payment_source !== 'google') {
            array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => 'dobL078Zl', 'message' => (isset($label_) ? 'payment_source' . ': ' . $label_ : 'payment_source') . " should match one of the following values [ web | apple | google ] but you provided the value {$payment_source}"]);
        }
        return $messages;
    }

    private static function _assert_os($os, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('gdTH2M_79B', isset($label_) ? 'os' . ':' . $label_ : 'os', $os));
        if ($os !== 'android' &&
            $os !== 'ios' &&
            $os !== 'web') {
            array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => 'gdTH2M_79B', 'message' => (isset($label_) ? 'os' . ': ' . $label_ : 'os') . " should match one of the following values [ android | ios | web ] but you provided the value {$os}"]);
        }
        return $messages;
    }

    private static function _assert_price($price, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('h9ISDDJ55O', isset($label_) ? 'price' . ':' . $label_ : 'price', $price));
        return $messages;
    }

    private static function _assert_experience_level($experience_level, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('kJBXPS-Rv', isset($label_) ? 'experience_level' . ':' . $label_ : 'experience_level', $experience_level));
        return $messages;
    }

    private static function _assert_experiment_id($experiment_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('lC_51KjNn', isset($label_) ? 'experiment_id' . ':' . $label_ : 'experiment_id', $experiment_id));
        return $messages;
    }

    private static function _assert_platform($platform, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('nl9EAj7rv8', isset($label_) ? 'platform' . ':' . $label_ : 'platform', $platform));
        if ($platform !== 'musora-app' &&
            $platform !== 'web' &&
            $platform !== 'pianote-app-legacy' &&
            $platform !== 'musora-app-legacy') {
            array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => 'nl9EAj7rv8', 'message' => (isset($label_) ? 'platform' . ': ' . $label_ : 'platform') . " should match one of the following values [ musora-app | web | pianote-app-legacy | musora-app-legacy ] but you provided the value {$platform}"]);
        }
        return $messages;
    }

    private static function _assert_refund_id($refund_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('o0vJDepdQ', isset($label_) ? 'refund_id' . ':' . $label_ : 'refund_id', $refund_id));
        return $messages;
    }

    private static function _assert_product_id($product_id, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_int('rCNeiWKKW', isset($label_) ? 'product_id' . ':' . $label_ : 'product_id', $product_id));
        return $messages;
    }

    private static function _assert_navigation_section($navigation_section, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('sU_wHRlyx', isset($label_) ? 'navigation_section' . ':' . $label_ : 'navigation_section', $navigation_section));
        return $messages;
    }

    private static function _assert_discount_tags_optional($discount_tags, $label_ = null)
    {
        $messages = [];
        if (isset($discount_tags)) {
            $messages = array_merge($messages, self::_avo_assert_list('sdKyEsLUw', 'discount_tags', $discount_tags));
            if (is_array($discount_tags)) {
                foreach($discount_tags as $key => $value) {
                }
            }
        }
        return $messages;
    }

    private static function _assert_experiment_name($experiment_name, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('tJUVCCMRo', isset($label_) ? 'experiment_name' . ':' . $label_ : 'experiment_name', $experiment_name));
        return $messages;
    }

    private static function _assert_filter_tag($filter_tag, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_string('u5UvdMoEN', isset($label_) ? 'filter_tag' . ':' . $label_ : 'filter_tag', $filter_tag));
        return $messages;
    }

    private static function _assert_checkout_token_optional($checkout_token, $label_ = null)
    {
        $messages = [];
        if (isset($checkout_token)) {
            $messages = array_merge($messages, self::_avo_assert_string('uCkpP8iaa', isset($label_) ? 'checkout_token' . ':' . $label_ : 'checkout_token', $checkout_token));
        }
        return $messages;
    }

    private static function _assert_discount($discount, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_float('xNbZ8gENn', isset($label_) ? 'discount' . ':' . $label_ : 'discount', $discount));
        return $messages;
    }

    private static function _assert_has_completed_onboarding($has_completed_onboarding, $label_ = null)
    {
        $messages = [];
        $messages = array_merge($messages, self::_avo_assert_bool('y4FX_D_aWP', isset($label_) ? 'has_completed_onboarding' . ':' . $label_ : 'has_completed_onboarding', $has_completed_onboarding));
        return $messages;
    }

    public static function onboarding_started($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            // debug console in Avo
            self::_invoke('FeaHCzH-x', '61a1add01bc5bd6805c6942efc2c7f91255984dd082beb358882364b6e46f4a0', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Started': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Started', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Started', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        ]);
    }

    public static function account_created($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_account_created_at($properties['account_created_at']));
            // debug console in Avo
            self::_invoke('P07BEO3Z8', '8ff69d322dd82d426c585aa01195bcc680c0a4057e04acb81abc0d2da2b0b89a', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Account Created': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Account Created', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter(
                [
                'account_created_at' => $properties['account_created_at'],
             ],
                function ($value) { return isset($value); }
            ), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->set_user_properties(
            $properties['user_id_'],
            [
            'account_created_at' => $properties['account_created_at'],
         ]
        );
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Account Created', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        ]);
    }

    public static function referral_invite_sent($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('SFvxiAyg2', '5124206bf7237db38860587d93560db2df3bd1098bb5a3cc75b73a831e0b4c4c', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Referral Invite Sent': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Referral Invite Sent', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Referral Invite Sent', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function referral_link_copied($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('l6EEHrFAm', 'd7f602004af4837ec9350edeb87717d39564b52761cb15238e77d5bd0c049473', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Referral Link Copied': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Referral Link Copied', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Referral Link Copied', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_about_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
            // debug console in Avo
            self::_invoke('TPjrjI22JG', '35beb042533a0c59162382ffebf512dd24fcb8f723384364b24bf37c0dd02b6e', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding About Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding About Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'is_skipped' => $properties['is_skipped'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding About Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'is_skipped' => $properties['is_skipped'],
        ]);
    }

    public static function onboarding_instrument_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('m-5bPn9dHs', '2a591eb78ae452fae68fa432122124bd94ec3b84296eef26e5530f6f33e7e75b', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Instrument Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Instrument Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Instrument Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_gear_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_gear_list($properties['gear_list']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('aPa8PWuKjC', '9a89e7187ccb44efe33aa64be46482e5f754048c8a593ae1bf5504f371bef2cd', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Gear Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Gear Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'gear_list' => $properties['gear_list'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Gear Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'gear_list' => $properties['gear_list'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_experience_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_experience_level($properties['experience_level']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('QGsppNv0OJ', '80d6589f17e008ad48653b371cb11fd8f55396eeba02e3bec0f710e0a11562d6', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Experience Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Experience Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'experience_level' => $properties['experience_level'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Experience Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'experience_level' => $properties['experience_level'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_genres_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_genre_list($properties['genre_list']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('t9Z83FSnYD', 'afc2963a61878fe8090c5761bf37315de6319cd1a6a82c6aa8751f065ea1ebc4', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Genres Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Genres Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'genre_list' => $properties['genre_list'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Genres Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'genre_list' => $properties['genre_list'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_topics_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_topic_list($properties['topic_list']));
            // debug console in Avo
            self::_invoke('ynS7ECZHra', '4bce907297d0d24deab5295759cdd9767147ee9195b843947b04f95d74dc8e50', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Topics Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Topics Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            'topic_list' => $properties['topic_list'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Topics Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        'topic_list' => $properties['topic_list'],
        ]);
    }

    public static function onboarding_skipped($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_step_skipped_optional($properties['step_skipped']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('JDGGcLaq4', 'b681d8f871beb6f22971c335ad52bcb7c46bdebec6169acb79c09f9ac27a96dc', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Skipped': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Skipped', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'step_skipped' => isset($properties['step_skipped']) ? $properties['step_skipped'] : null,
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Skipped', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'step_skipped' => isset($properties['step_skipped']) ? $properties['step_skipped'] : null,
        'brand' => $properties['brand'],
        ]);
    }

    public static function onboarding_goals_step_completed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_has_completed_onboarding($properties['has_completed_onboarding']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_goals_list($properties['goals_list']));
            // debug console in Avo
            self::_invoke('QBhZxvp8po', 'bc4bbe5c1f7a932aed0f939f83b097fe15b9e3c852b1b729ae24c1e8dae4429b', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Onboarding Goals Step Completed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Goals Step Completed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            'goals_list' => $properties['goals_list'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter(
                [
                'has_completed_onboarding' => $properties['has_completed_onboarding'],
             ],
                function ($value) { return isset($value); }
            ), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->set_user_properties(
            $properties['user_id_'],
            [
            'has_completed_onboarding' => $properties['has_completed_onboarding'],
         ]
        );
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Goals Step Completed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        'goals_list' => $properties['goals_list'],
        ]);
    }

    public static function referral_page_viewed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            // debug console in Avo
            self::_invoke('fMpb6d55W5', '441f619f14612140b74d68dd6378175c9f61e71e99d294571e9e739051ad347e', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Referral Page Viewed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Referral Page Viewed', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Referral Page Viewed', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        ]);
    }

    public static function order_placed($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_checkout_token_optional($properties['checkout_token']));
            $messages = array_merge($messages, self::_assert_order_id($properties['order_id']));
            $messages = array_merge($messages, self::_assert_subtotal($properties['subtotal']));
            $messages = array_merge($messages, self::_assert_total($properties['total']));
            $messages = array_merge($messages, self::_assert_revenue($properties['revenue']));
            $messages = array_merge($messages, self::_assert_shipping($properties['shipping']));
            $messages = array_merge($messages, self::_assert_tax($properties['tax']));
            $messages = array_merge($messages, self::_assert_discount($properties['discount']));
            $messages = array_merge($messages, self::_assert_discount_tags_optional($properties['discount_tags']));
            $messages = array_merge($messages, self::_assert_currency($properties['currency']));
            $messages = array_merge($messages, self::_assert_products($properties['products']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_payment_source($properties['payment_source']));
            // debug console in Avo
            self::_invoke('XRJCk6WrcZ', '4da80c7f8d92c97af7b976f56c67089ea9e6d9748b0c9b59eaad798c1723401a', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Order Placed': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Order Placed', Event props: ". print_r(array_filter([
            'checkout_token' => isset($properties['checkout_token']) ? $properties['checkout_token'] : null,
            'order_id' => $properties['order_id'],
            'subtotal' => $properties['subtotal'],
            'total' => $properties['total'],
            'revenue' => $properties['revenue'],
            'shipping' => $properties['shipping'],
            'tax' => $properties['tax'],
            'discount' => $properties['discount'],
            'discount_tags' => isset($properties['discount_tags']) ? $properties['discount_tags'] : null,
            'currency' => $properties['currency'],
            'products' =>
            array_map(function ($value) {
                return array_filter([
                    'product_id' => $value['product_id'],
                    'product_name' => $value['product_name'],
                    'brand' => $value['brand'],
                    'price' => $value['price'],
                    'quantity' => $value['quantity'],
                    'variant_id' => $value['variant_id'],
                    'sku' => $value['sku'],
                ], function ($value) { return isset($value); });
            }, $properties['products']),
            'brand' => $properties['brand'],
            'payment_source' => $properties['payment_source'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Order Placed', [
        'checkout_token' => isset($properties['checkout_token']) ? $properties['checkout_token'] : null,
        'order_id' => $properties['order_id'],
        'subtotal' => $properties['subtotal'],
        'total' => $properties['total'],
        'revenue' => $properties['revenue'],
        'shipping' => $properties['shipping'],
        'tax' => $properties['tax'],
        'discount' => $properties['discount'],
        'discount_tags' => isset($properties['discount_tags']) ? $properties['discount_tags'] : null,
        'currency' => $properties['currency'],
        'products' =>
        array_map(function ($value) {
            return array_filter([
                'product_id' => $value['product_id'],
                'product_name' => $value['product_name'],
                'brand' => $value['brand'],
                'price' => $value['price'],
                'quantity' => $value['quantity'],
                'variant_id' => $value['variant_id'],
                'sku' => $value['sku'],
            ], function ($value) { return isset($value); });
        }, $properties['products']),
        'brand' => $properties['brand'],
        'payment_source' => $properties['payment_source'],
        ]);
    }

    public static function order_refunded($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_order_id($properties['order_id']));
            $messages = array_merge($messages, self::_assert_currency($properties['currency']));
            $messages = array_merge($messages, self::_assert_products_optional($properties['products']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_refund_id($properties['refund_id']));
            $messages = array_merge($messages, self::_assert_refund_amount($properties['refund_amount']));
            // debug console in Avo
            self::_invoke('Y6cRlssS6E', '500e388dc3bbaf16be1f0ad61ff0e9378cdd3e8604dc9fd62a4cde3b447e5870', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Order Refunded': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Order Refunded', Event props: ". print_r(array_filter([
            'order_id' => $properties['order_id'],
            'currency' => $properties['currency'],
            "products" => isset($properties['products']) ?
            array_map(function ($value) {
                return array_filter([
                    'product_id' => $value['product_id'],
                    'product_name' => $value['product_name'],
                    'brand' => $value['brand'],
                    'price' => $value['price'],
                    'quantity' => $value['quantity'],
                    'variant_id' => $value['variant_id'],
                    'sku' => $value['sku'],
                ], function ($value) { return isset($value); });
            }, $properties['products']) : $properties['products'],
            'brand' => $properties['brand'],
            'refund_id' => $properties['refund_id'],
            'refund_amount' => $properties['refund_amount'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Order Refunded', [
        'order_id' => $properties['order_id'],
        'currency' => $properties['currency'],
        "products" => isset($properties['products']) ?
        array_map(function ($value) {
            return array_filter([
                'product_id' => $value['product_id'],
                'product_name' => $value['product_name'],
                'brand' => $value['brand'],
                'price' => $value['price'],
                'quantity' => $value['quantity'],
                'variant_id' => $value['variant_id'],
                'sku' => $value['sku'],
            ], function ($value) { return isset($value); });
        }, $properties['products']) : $properties['products'],
        'brand' => $properties['brand'],
        'refund_id' => $properties['refund_id'],
        'refund_amount' => $properties['refund_amount'],
        ]);
    }

    public static function experimentation_branch_assigned($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_experiment_id($properties['experiment_id']));
            $messages = array_merge($messages, self::_assert_experiment_name($properties['experiment_name']));
            $messages = array_merge($messages, self::_assert_branch_id($properties['branch_id']));
            $messages = array_merge($messages, self::_assert_branch_name($properties['branch_name']));
            // debug console in Avo
            self::_invoke('VSv7MJkBYz', '5952b4307da89b270964e76fecf479a8d4926c0bedb3bcb4acafe43cebd02223', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Experimentation Branch Assigned': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Experimentation Branch Assigned', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'experiment_id' => $properties['experiment_id'],
            'experiment_name' => $properties['experiment_name'],
            'branch_id' => $properties['branch_id'],
            'branch_name' => $properties['branch_name'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Experimentation Branch Assigned', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'experiment_id' => $properties['experiment_id'],
        'experiment_name' => $properties['experiment_name'],
        'branch_id' => $properties['branch_id'],
        'branch_name' => $properties['branch_name'],
        ]);
    }

    public static function filter_applied($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_filters($properties['filters']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_navigation_section($properties['navigation_section']));
            // debug console in Avo
            self::_invoke('FBhKVZCZT4', '292d08abbe3efffd93b8d7f57e3b44329c7c0942f88f9d093ea80afcdb895aae', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Filter Applied': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Filter Applied', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'filters' =>
            array_map(function ($value) {
                return array_filter([
                    'filter_category' => $value['filter_category'],
                    'filter_tag' => $value['filter_tag'],
                ], function ($value) { return isset($value); });
            }, $properties['filters']),
            'brand' => $properties['brand'],
            'navigation_section' => $properties['navigation_section'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Filter Applied', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'filters' =>
        array_map(function ($value) {
            return array_filter([
                'filter_category' => $value['filter_category'],
                'filter_tag' => $value['filter_tag'],
            ], function ($value) { return isset($value); });
        }, $properties['filters']),
        'brand' => $properties['brand'],
        'navigation_section' => $properties['navigation_section'],
        ]);
    }

    public static function sorting_applied($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_sorting_type($properties['sorting_type']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_navigation_section($properties['navigation_section']));
            // debug console in Avo
            self::_invoke('vg7bUEFPIO', '46293a68a8fc34a60ad502d2c5d48a9a2b34243ed160f27220f399e6b6f6f4f0', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Sorting Applied': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Sorting Applied', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'sorting_type' => $properties['sorting_type'],
            'brand' => $properties['brand'],
            'navigation_section' => $properties['navigation_section'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Sorting Applied', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'sorting_type' => $properties['sorting_type'],
        'brand' => $properties['brand'],
        'navigation_section' => $properties['navigation_section'],
        ]);
    }

    public static function filter_group_applied($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_filter_group($properties['filter_group']));
            $messages = array_merge($messages, self::_assert_navigation_section($properties['navigation_section']));
            // debug console in Avo
            self::_invoke('uqpa2Us2LH', '218fa72288f28e78932428445f2224ba063efca9738b1ece61a608005b9dc9c9', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Filter Group Applied': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Filter Group Applied', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            'filter_group' => $properties['filter_group'],
            'navigation_section' => $properties['navigation_section'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Filter Group Applied', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        'filter_group' => $properties['filter_group'],
        'navigation_section' => $properties['navigation_section'],
        ]);
    }

    public static function homepage_content_clicked($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_homepage_section($properties['homepage_section']));
            $messages = array_merge($messages, self::_assert_content_id_optional($properties['content_id']));
            // debug console in Avo
            self::_invoke('dYP15nuFxw', 'e6edc51d3fec1345362d92cd87a54988614b4b557a97a1e0c56e2020eb40f5a7', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Homepage Content Clicked': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Homepage Content Clicked', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            'homepage_section' => $properties['homepage_section'],
            'content_id' => isset($properties['content_id']) ? $properties['content_id'] : null,
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Homepage Content Clicked', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        'homepage_section' => $properties['homepage_section'],
        'content_id' => isset($properties['content_id']) ? $properties['content_id'] : null,
        ]);
    }

    public static function homepage_section_see_all_clicked($properties = [])
    {
        // assert properties
        if (self::$__AVO_ENV__ !== 'prod') {
            $messages = [];
            $messages = array_merge($messages, self::_assert_os($properties['os']));
            $messages = array_merge($messages, self::_assert_platform($properties['platform']));
            $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
            $messages = array_merge($messages, self::_assert_brand($properties['brand']));
            $messages = array_merge($messages, self::_assert_homepage_section($properties['homepage_section']));
            // debug console in Avo
            self::_invoke('ayqjU62wR7', '0c948c17c20e9fb28728ad86217a92d1ce5cd92c4cceb6db34478c41c05b36d4', $messages);
            if (self::$__STRICT__) {
                // throw exception if messages is not empty
                if (count($messages) > 0) {
                    throw new \UnexpectedValueException("Error sending event 'Homepage Section See All Clicked': {$messages[0]['message']}");
                }
            } else {
                if (self::$__VERBOSE__) {
                    foreach($messages as $m) {
                        self::$__LOGGER__->error("[avo] {$m['message']}");
                    }
                }
            }
        }

        if (self::$__AVO_ENV__ !== 'prod') {
            self::$__LOGGER__->info("[avo] Event sent: 'Homepage Section See All Clicked', Event props: ". print_r(array_filter([
            'os' => $properties['os'],
            'platform' => $properties['platform'],
            'brand' => $properties['brand'],
            'homepage_section' => $properties['homepage_section'],
            ], function ($value) { return isset($value); }), true) . ", User props: " . print_r(array_filter([], function ($value) { return isset($value); }), true));
        }

        // destination rudder_stack
        self::$rudder_stackDestination->log_event($properties['user_id_'], 'Homepage Section See All Clicked', [
        'os' => $properties['os'],
        'platform' => $properties['platform'],
        'brand' => $properties['brand'],
        'homepage_section' => $properties['homepage_section'],
        ]);
    }

}
if (!function_exists('json_encode')) {
    throw new \Exception('Avo needs the JSON PHP extension.');
}
// AVOMODULEMAP:"Avo"
// AVOEVENTMAP:["onboarding_started","account_created","referral_invite_sent","referral_link_copied","onboarding_about_step_completed","onboarding_instrument_step_completed","onboarding_gear_step_completed","onboarding_experience_step_completed","onboarding_genres_step_completed","onboarding_topics_step_completed","onboarding_skipped","onboarding_goals_step_completed","referral_page_viewed","order_placed","order_refunded","experimentation_branch_assigned","filter_applied","sorting_applied","filter_group_applied","homepage_content_clicked","homepage_section_see_all_clicked"]
