<?php /** @noinspection ALL */
// Generated by Avo VERSION 120.0.0. You should never have to make changes to this file.
// If you find yourself in the situation where you have to edit the file please contact us at hi@avo.app.
// If you encounter a git conflict in this file run `avo pull` and it will be resolved automatically.

class Avo
{
    private static $__VERBOSE__ = TRUE;
    private static $__STRICT__ = TRUE;
    private static $__AVO_ENV__ = NULL;

    /** @var \Psr\Log\LoggerInterface */
    private static $__LOGGER__ = NULL;

    // assertion prelude
    private static function _avo_assert_int($property_id, $property_name, $num)
    {
        if (!is_int($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedIntType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type int but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_long($property_id, $property_name, $num)
    {
        if (!is_long($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedLongType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type long but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_float($property_id, $property_name, $num)
    {
        if (!is_float($num)) {
            $actual_type = gettype($num);
            return [['tag' => 'expectedFloatType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type float but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_object($property_id, $property_name, $value)
    {
        if (!is_array($value) || array_keys($value) === range(0, count($value) - 1)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedObjectType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type associative array but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_string($property_id, $property_name, $value)
    {
        if (!is_string($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedStringType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type string but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_bool($property_id, $property_name, $value)
    {
        if (!is_bool($value)) {
            $actual_type = gettype($value);
            return [['tag' => 'expectedBoolType', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type boolean but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_list($property_id, $property_name, $list)
    {
        if (!is_array($list)) {
            $actual_type = gettype($list);
            return [['tag' => 'expectedList', 'propertyId' => $property_id, 'message' => "{$property_name} should be of type list but you provided type {$actual_type}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_min($property_id, $property_name, $min, $value)
    {
        if ($value < $min) {
            return [['tag' => 'expectedMin', 'propertyId' => $property_id, 'message' => "{$property_name} has a minimum value of {$min} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }

    private static function _avo_assert_max($property_id, $property_name, $max, $value)
    {
        if ($value > $max) {
            return [['tag' => 'expectedMax', 'propertyId' => $property_id, 'message' => "{$property_name} has a maximum value of {$max} but you provided the value {$value}"]];
        } else {
            return [];
        }
    }



    private static $samplingRate = 1.0;

    private static function _invoke($event_id, $hash, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'f3MYVlnfvvInPEinLTIl',
                        'br' => 'ycp3d9CRQ',
                        'en' => self::$__AVO_ENV__,
                        'ev' => $event_id,
                        'ha' => $hash,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                        'or' => 'event',
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, TRUE);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }

    private static function _invoke_meta($type, $messages)
    {
        if (self::$samplingRate > 0) {
            if ((mt_rand(0, mt_getrandmax() - 1) / mt_getrandmax()) < self::$samplingRate) {
                try {
                    $ch = curl_init('https://api.avo.app/i');
                    $data = [
                        'ac' => 'f3MYVlnfvvInPEinLTIl',
                        'br' => 'ycp3d9CRQ',
                        'en' => self::$__AVO_ENV__,
                        'ty' => $type,
                        'sc' => '1cMjCpEPIvTt6xkXe7Fi',
                        'se' => date("c"),
                        'so' => 'Z-PFv6Lo9',
                        'va' => count($messages) == 0,
                        'me' => array_map(function($m) { return ['tag' => $m['tag'], 'propertyId' => $m['propertyId']]; }, $messages),
                    ];

                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
                    $response = curl_exec($ch);
                    $result = json_decode($response, TRUE);
                    $new_sampling_rate = $result['sa'];
                    if ($new_sampling_rate >= 0.0 && $new_sampling_rate <= 1.0) {
                        self::$samplingRate = $new_sampling_rate;
                    }
                } catch (Throwable $e) {
                } catch (Exception $e) {
                }
            }
        }
    }


     // instance for rudder_stack destination
     private static $rudder_stackDestination = NULL;

     public static function init_avo($options)
     {
         self::$__STRICT__ = isset($options['strict']) ? $options['strict'] : TRUE;
         self::$__VERBOSE__ = isset($options['verbose']) ? $options['verbose'] : TRUE;
         self::$__AVO_ENV__ = $options['env'];
         self::$__LOGGER__ = $options['logger'];

         self::$rudder_stackDestination = $options['rudder_stack_instance'];
         if (method_exists(self::$rudder_stackDestination, 'make')) {
             if (self::$__AVO_ENV__ === 'prod') {
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             } else if (self::$__AVO_ENV__ === 'dev') {
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             } else {
                 self::$__LOGGER__->error("[avo] No staging key is set for RudderStack. Head to destination settings in Avo to set a staging key");
                 self::$rudder_stackDestination->make(self::$__AVO_ENV__, null);
             }
         }
         if (self::$__AVO_ENV__ !== 'prod') {
             // debug console in Avo
             self::_invoke_meta('init', []);
         }
     }

     private static function _assert_step_skipped($step_skipped, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('3VO48nTzt-', isset($label_) ? 'step_skipped' . ':' . $label_ : 'step_skipped', $step_skipped));
         if ($step_skipped !== 'gear' &&
             $step_skipped !== 'experience' &&
             $step_skipped !== 'genres' &&
             $step_skipped !== 'topics' &&
             $step_skipped !== 'goals') {
             array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '3VO48nTzt-', 'message' => (isset($label_) ? 'step_skipped' . ': ' . $label_ : 'step_skipped') . " should match one of the following values [ gear | experience | genres | topics | goals ] but you provided the value {$step_skipped}"]);
         }
         return $messages;
     }

     private static function _assert_brand($brand, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('5mOEXJ648', isset($label_) ? 'brand' . ':' . $label_ : 'brand', $brand));
         if ($brand !== 'drumeo' &&
             $brand !== 'guitareo' &&
             $brand !== 'musora' &&
             $brand !== 'recordeo' &&
             $brand !== 'singeo' &&
             $brand !== 'pianote') {
             array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => '5mOEXJ648', 'message' => (isset($label_) ? 'brand' . ': ' . $label_ : 'brand') . " should match one of the following values [ drumeo | guitareo | musora | recordeo | singeo | pianote ] but you provided the value {$brand}"]);
         }
         return $messages;
     }

     private static function _assert_cio_id_guitareo($cio_id_guitareo, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('9jUzgBMDO', isset($label_) ? 'cio_id_guitareo' . ':' . $label_ : 'cio_id_guitareo', $cio_id_guitareo));
         return $messages;
     }

     private static function _assert_gear_list($gear_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('Fx30ZyaXN', 'gear_list', $gear_list));
         if (is_array($gear_list)) {
             foreach($gear_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_genre_list($genre_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('N5hB7Rf5K', 'genre_list', $genre_list));
         if (is_array($genre_list)) {
             foreach($genre_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_is_skipped($is_skipped, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_bool('ZSKmyfbiL-', isset($label_) ? 'is_skipped' . ':' . $label_ : 'is_skipped', $is_skipped));
         return $messages;
     }

     private static function _assert_goals_list($goals_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('a97p4BAJd', 'goals_list', $goals_list));
         if (is_array($goals_list)) {
             foreach($goals_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_user_id_($user_id_, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('avo-enriched-server-user-id', isset($label_) ? 'User Id' . ':' . $label_ : 'User Id', $user_id_));
         return $messages;
     }

     private static function _assert_topic_list($topic_list, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_list('bjLJ9Wifx', 'topic_list', $topic_list));
         if (is_array($topic_list)) {
             foreach($topic_list as $key=>$value) {
             }
         }
         return $messages;
     }

     private static function _assert_cio_id_singeo($cio_id_singeo, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('eFucK_Ilt', isset($label_) ? 'cio_id_singeo' . ':' . $label_ : 'cio_id_singeo', $cio_id_singeo));
         return $messages;
     }

     private static function _assert_os($os, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('gdTH2M_79B', isset($label_) ? 'os' . ':' . $label_ : 'os', $os));
         if ($os !== 'android' &&
             $os !== 'ios' &&
             $os !== 'web') {
             array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => 'gdTH2M_79B', 'message' => (isset($label_) ? 'os' . ': ' . $label_ : 'os') . " should match one of the following values [ android | ios | web ] but you provided the value {$os}"]);
         }
         return $messages;
     }

     private static function _assert_experience_level($experience_level, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('kJBXPS-Rv', isset($label_) ? 'experience_level' . ':' . $label_ : 'experience_level', $experience_level));
         return $messages;
     }

     private static function _assert_cio_id_drumeo($cio_id_drumeo, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('m71bLGSgl', isset($label_) ? 'cio_id_drumeo' . ':' . $label_ : 'cio_id_drumeo', $cio_id_drumeo));
         return $messages;
     }

     private static function _assert_cio_id_pianote($cio_id_pianote, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('mT5Gx2vFz', isset($label_) ? 'cio_id_pianote' . ':' . $label_ : 'cio_id_pianote', $cio_id_pianote));
         return $messages;
     }

     private static function _assert_platform($platform, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('nl9EAj7rv8', isset($label_) ? 'platform' . ':' . $label_ : 'platform', $platform));
         if ($platform !== 'drumeo-app' &&
             $platform !== 'musora-app' &&
             $platform !== 'pianote-app' &&
             $platform !== 'web') {
             array_push($messages, ['tag' => 'expectedStringMatch', 'propertyId' => 'nl9EAj7rv8', 'message' => (isset($label_) ? 'platform' . ': ' . $label_ : 'platform') . " should match one of the following values [ drumeo-app | musora-app | pianote-app | web ] but you provided the value {$platform}"]);
         }
         return $messages;
     }

     private static function _assert_cio_id_musora($cio_id_musora, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_string('rOAkB_jgLw', isset($label_) ? 'cio_id_musora' . ':' . $label_ : 'cio_id_musora', $cio_id_musora));
         return $messages;
     }

     private static function _assert_has_completed_onboarding($has_completed_onboarding, $label_ = NULL)
     {
         $messages = [];
         $messages = array_merge($messages, self::_avo_assert_bool('y4FX_D_aWP', isset($label_) ? 'has_completed_onboarding' . ':' . $label_ : 'has_completed_onboarding', $has_completed_onboarding));
         return $messages;
     }

     public static function onboarding_started($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('FeaHCzH-x', '45c1808ab0ff86db5590ace5fde81f937212b5bb3bb4b98fa2472620d58166bc', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Started': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Started', Event props: ". print_r(array_filter([
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Started', [
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function account_created($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('P07BEO3Z8', '027a5db1196c92e5e37a1a04a8f3e165207efe838aebb3f3a3fc02fb5a63b86c', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Account Created': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Account Created', Event props: ". print_r(array_filter([
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Account Created', [
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_about_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_is_skipped($properties['is_skipped']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('TPjrjI22JG', 'd764b3327b3267036f8165b6f44afa37559cc4eac7e5c342a6a0564671a1b9c3', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding About Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding About Step Completed', Event props: ". print_r(array_filter([
             'is_skipped' => $properties['is_skipped'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding About Step Completed', [
         'is_skipped' => $properties['is_skipped'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_instrument_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('m-5bPn9dHs', '3b6927075072b3d241352ba8b92062b9de104e9ce46ef3fbb8fb94dcdfaf23fb', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Instrument Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Instrument Step Completed', Event props: ". print_r(array_filter([
             'brand' => $properties['brand'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Instrument Step Completed', [
         'brand' => $properties['brand'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_gear_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_gear_list($properties['gear_list']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('aPa8PWuKjC', '2c822028e23d7ba6a52f6b9597c6a099c67c9e3c0dcc31f45f3b92003fd4b11d', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Gear Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Gear Step Completed', Event props: ". print_r(array_filter([
             'gear_list' => $properties['gear_list'],
             'brand' => $properties['brand'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Gear Step Completed', [
         'gear_list' => $properties['gear_list'],
         'brand' => $properties['brand'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_experience_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_experience_level($properties['experience_level']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('QGsppNv0OJ', 'cb421245b49ee1f5aa3f8d76393f8c9bdf2d69c8eb4f1f33787c38379fdea84a', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Experience Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Experience Step Completed', Event props: ". print_r(array_filter([
             'experience_level' => $properties['experience_level'],
             'brand' => $properties['brand'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Experience Step Completed', [
         'experience_level' => $properties['experience_level'],
         'brand' => $properties['brand'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_genres_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_genre_list($properties['genre_list']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('t9Z83FSnYD', '4398aa786c1f3412a812d41cbe280b782fb590f288da22fcf0cf62cdb968383f', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Genres Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Genres Step Completed', Event props: ". print_r(array_filter([
             'genre_list' => $properties['genre_list'],
             'brand' => $properties['brand'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Genres Step Completed', [
         'genre_list' => $properties['genre_list'],
         'brand' => $properties['brand'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_topics_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_topic_list($properties['topic_list']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('ynS7ECZHra', '52e6ab6864ec9bb26cc5f31e6fe0cffb61b1ec956cbd03ec758a0e579aae13ed', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Topics Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Topics Step Completed', Event props: ". print_r(array_filter([
             'brand' => $properties['brand'],
             'topic_list' => $properties['topic_list'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Topics Step Completed', [
         'brand' => $properties['brand'],
         'topic_list' => $properties['topic_list'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_skipped($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_step_skipped($properties['step_skipped']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('JDGGcLaq4', '449bec6379abe592b389a99c36b220ff94b751e70ea2a614974e07b553a086b5', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Skipped': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Skipped', Event props: ". print_r(array_filter([
             'step_skipped' => $properties['step_skipped'],
             'brand' => $properties['brand'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter([], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Skipped', [
         'step_skipped' => $properties['step_skipped'],
         'brand' => $properties['brand'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

     public static function onboarding_goals_step_completed($properties = [])
     {
         // assert properties
         if (self::$__AVO_ENV__ !== 'prod') {
             $messages = [];
             $messages = array_merge($messages, self::_assert_user_id_($properties['user_id_']));
             $messages = array_merge($messages, self::_assert_has_completed_onboarding($properties['has_completed_onboarding']));
             $messages = array_merge($messages, self::_assert_brand($properties['brand']));
             $messages = array_merge($messages, self::_assert_goals_list($properties['goals_list']));
             $messages = array_merge($messages, self::_assert_os($properties['os']));
             $messages = array_merge($messages, self::_assert_platform($properties['platform']));
             $messages = array_merge($messages, self::_assert_cio_id_musora($properties['cio_id_musora']));
             $messages = array_merge($messages, self::_assert_cio_id_drumeo($properties['cio_id_drumeo']));
             $messages = array_merge($messages, self::_assert_cio_id_singeo($properties['cio_id_singeo']));
             $messages = array_merge($messages, self::_assert_cio_id_pianote($properties['cio_id_pianote']));
             $messages = array_merge($messages, self::_assert_cio_id_guitareo($properties['cio_id_guitareo']));
             // debug console in Avo
             self::_invoke('QBhZxvp8po', 'f63e017dc9731ca0b87bbcc283f4a0b6b4df99b88c58cb09a9e3c44778bdfb12', $messages);
             if (self::$__STRICT__) {
                 // throw exception if messages is not empty
                 if (count($messages) > 0) {
                     throw new \UnexpectedValueException("Error sending event 'Onboarding Goals Step Completed': {$messages[0]['message']}");
                 }
             } else {
                 if (self::$__VERBOSE__) {
                     foreach($messages as $m) {
                         self::$__LOGGER__->error("[avo] {$m['message']}");
                     }
                 }
             }
         }

         if (self::$__AVO_ENV__ !== 'prod') {
             self::$__LOGGER__->info("[avo] Event sent: 'Onboarding Goals Step Completed', Event props: ". print_r(array_filter([
             'brand' => $properties['brand'],
             'goals_list' => $properties['goals_list'],
             'os' => $properties['os'],
             'platform' => $properties['platform'],
             'cio_id_musora' => $properties['cio_id_musora'],
             'cio_id_drumeo' => $properties['cio_id_drumeo'],
             'cio_id_singeo' => $properties['cio_id_singeo'],
             'cio_id_pianote' => $properties['cio_id_pianote'],
             'cio_id_guitareo' => $properties['cio_id_guitareo'],
             ], function($value) { return isset($value); }), TRUE) . ", User props: " . print_r(array_filter(
             [
                 'has_completed_onboarding' => $properties['has_completed_onboarding'],
             ], function($value) { return isset($value); }), TRUE));
         }

         // destination rudder_stack
         self::$rudder_stackDestination->set_user_properties($properties['user_id_'],
         [
             'has_completed_onboarding' => $properties['has_completed_onboarding'],
         ]);
         self::$rudder_stackDestination->log_event($properties['user_id_'], 'Onboarding Goals Step Completed', [
         'brand' => $properties['brand'],
         'goals_list' => $properties['goals_list'],
         'os' => $properties['os'],
         'platform' => $properties['platform'],
         'cio_id_musora' => $properties['cio_id_musora'],
         'cio_id_drumeo' => $properties['cio_id_drumeo'],
         'cio_id_singeo' => $properties['cio_id_singeo'],
         'cio_id_pianote' => $properties['cio_id_pianote'],
         'cio_id_guitareo' => $properties['cio_id_guitareo'],
         ]);
     }

}
if (!function_exists('json_encode')) {
    throw new \Exception('Avo needs the JSON PHP extension.');
}
// AVOMODULEMAP:"Avo"
// AVOEVENTMAP:["onboarding_started","account_created","onboarding_about_step_completed","onboarding_instrument_step_completed","onboarding_gear_step_completed","onboarding_experience_step_completed","onboarding_genres_step_completed","onboarding_topics_step_completed","onboarding_skipped","onboarding_goals_step_completed"]
