#!/bin/sh
printf "\nRunning php-cs-fixer in check mode\n"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    FILES=$(git status --porcelain | grep -E '^[AM].*\.php$' | cut -c 3- | tr '\n' ' ')
    results="php-cs-fixer-results.txt"
    if [ ! -z "$FILES" ]; then
        rm -f $results
        docker exec --workdir /app/musora-web-platform railenvironmentdocker_apache-php-fpm-8 $PHP_CS_FIXER check --config=.php-cs-fixer.php ${FILES} > $results
        if  grep "Found 0 of " $results
        then
            echo ""
        else
            echo "Run 'bash .git/hooks/php-cs-fixer' to fix files then recommit. Or run 'git commit --no-verify' to skip verification"
            exit 1
        fi
        rm -f $results
    fi
else
    echo ""
    echo "Please install php-cs-fixer:"
    echo ""
    echo "  composer install"
    echo ""
    exit 1
fi
