@php
    $bonuses = [
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/acdc-back-in-black.png',
            'artist' => 'AC/DC',
            'song' => "Back In Black",
            'soundslice' => '7ZnVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/bon-jovi-livin-on-a-prayer.jpg',
            'artist' => 'Bon Jovi',
            'song' => "Livin’ On A Prayer",
            'soundslice' => '162928',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/260310-card-thumbnail-maxres-1592340581.jpg',
            'artist' => 'B.B. King',
            'song' => "The Thrill Is Gone",
            'soundslice' => 'gStVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/203872-card-thumbnail-maxres-1592341418.jpg',
            'artist' => 'Bee Gees',
            'song' => "Stayin’ Alive",
            'soundslice' => '169227',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/boston-more-than-a-feeling.jpg',
            'artist' => 'Boston',
            'song' => "More Than A Feeling",
            'soundslice' => '182346',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/coldplay-clocks.jpg',
            'artist' => 'Coldplay',
            'song' => "Clocks",
            'soundslice' => '229565',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/def-leppard-rock-of-ages.jpg',
            'artist' => 'Def Leppard',
            'song' => "Rock Of Ages",
            'soundslice' => 'Q-Cfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-dec/album-art/dire-straits-money-for-nothing.jpg',
            'artist' => 'Dire Straits',
            'song' => "Money For Nothing",
            'soundslice' => 'GjWfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/fleetwood-mac-go-your-own-way.jpg',
            'artist' => 'Fleetwood Mac',
            'song' => "Go Your Own Way",
            'soundslice' => '5kffc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/foo-fighters-my-hero.jpg',
            'artist' => 'Foo Fighters',
            'song' => "My Hero",
            'soundslice' => 'Yz4fc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2021-jan/album-art/green-day-wake-me-up-when-september-ends.jpg',
            'artist' => 'Green Day',
            'song' => "Holiday",
            'soundslice' => '-CFfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/guns-n-roses-paradise-city.jpg',
            'artist' => 'Guns N’ Roses',
            'song' => "Paradise City",
            'soundslice' => 'W8gVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/journey-separate-ways-worlds-apart.jpg',
            'artist' => 'Journey',
            'song' => "Separate Ways (Worlds Apart)",
            'soundslice' => 'p6gVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/kiss-i-was-made-for-lovin-you.jpg',
            'artist' => 'KISS',
            'song' => "I Was Made For Lovin’ You",
            'soundslice' => 'CcgVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2021-jan/album-art/led-zeppelin-stairway-to-heaven.jpg',
            'artist' => 'Led Zeppelin',
            'song' => "When The Levee Breaks",
            'soundslice' => 'Y3Ffc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/lenny-kravitz-are-you-gonna-go-my-way.jpg',
            'artist' => 'Lenny Kravitz',
            'song' => "Are You Gonna Go My Way",
            'soundslice' => 'hkgVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-dec/album-art/linkin-park-numb.jpg',
            'artist' => 'Linkin Park',
            'song' => "Numb",
            'soundslice' => '1nZfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/lynyrd-skynyrd-sweet-home-alabama.jpg',
            'artist' => 'Lynyrd Skynyrd',
            'song' => "Sweet Home Alabama",
            'soundslice' => '162936',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/megadeth-Hangar-18.jpg',
            'artist' => 'Megadeth',
            'song' => "Hangar 18",
            'soundslice' => '3xCfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/metallica-nothing-else-matters.jpg',
            'artist' => 'Metallica',
            'song' => "Nothing Else Matters",
            'soundslice' => 'gwgVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/260492-card-thumbnail-maxres-1593555946.jpg',
            'artist' => 'Michael Jackson',
            'song' => "Beat It",
            'soundslice' => '229610',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/muse-hysteria.jpg',
            'artist' => 'Muse',
            'song' => "Hysteria",
            'soundslice' => '8YgVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/nirvana-smells-like-teen-spirit.jpg',
            'artist' => 'Nirvana',
            'song' => "Smells Like Teen Spirit",
            'soundslice' => '1D6Vc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/paul-simon-50-ways-to-leave-your-lover.jpg',
            'artist' => 'Paul Simon',
            'song' => "50 Ways To Leave Your Lover",
            'soundslice' => '176791',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/pink-floyd-money.jpeg',
            'artist' => 'Pink Floyd',
            'song' => "Money",
            'soundslice' => '200747',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/queen-another-one-bites-the-dusk.jpeg',
            'artist' => 'Queen',
            'song' => "Another One Bites The Dust",
            'soundslice' => 'FzgVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-dec/album-art/red-hot-chili-peppers-snow-hey-oh-o.jpg',
            'artist' => 'Red Hot Chili Peppers',
            'song' => "Snow (Hey Oh)",
            'soundslice' => '9DLfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/rush-Limelight.jpg',
            'artist' => 'Rush',
            'song' => "Limelight",
            'soundslice' => 'kjRfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/steve-miller-Take-The-Money-And-Run.jpg',
            'artist' => 'Steve Miller Band',
            'song' => "Take The Money And Run",
            'soundslice' => 'X-1fc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/stevie-wonder-superstition.jpg',
            'artist' => 'Stevie Wonder',
            'song' => "Superstition",
            'soundslice' => 'qWcfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/system-of-a-down-toxicity.jpg',
            'artist' => 'System Of A Down',
            'song' => "Chop Suey!",
            'soundslice' => '163133',
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/the-beatles-here-comes-the-sun.jpg',
            'artist' => 'The Beatles',
            'song' => "Here Comes The Sun",
            'soundslice' => 'RZhVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/the-rolling-stones-i-cant-get-no-satisfaction.jpg',
            'artist' => 'The Rolling Stones',
            'song' => "(I Can’t Get No) Satisfaction",
            'soundslice' => 'h8gVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2021-feb/album-art/the-who-baba-o-riley.jpg',
            'artist' => 'The Who',
            'song' => "Baba O’Riley",
            'soundslice' => '-dhfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/tool-forty-six-and-2.jpg',
            'artist' => 'Tool',
            'song' => "Forty Six And 2",
            'soundslice' => 'SQvVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/toto-rosanna.jpg',
            'artist' => 'Toto',
            'song' => "Rosanna",
            'soundslice' => 'K8nVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/twenty-one-pilots-heathens.jpg',
            'artist' => 'Twenty One Pilots',
            'song' => "Heathens",
            'soundslice' => 'MN5Vc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/u2-sunday-bloody-sunday.jpg',
            'artist' => 'U2',
            'song' => "Sunday Bloody Sunday",
            'soundslice' => 'GVlfc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/van-halen-jump.jpg',
            'artist' => 'Van Halen',
            'song' => "Jump",
            'soundslice' => 'VN5Vc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/zz-top-sharp-dressed-man.jpg',
            'artist' => 'ZZ Top',
            'song' => "Sharp Dressed Man",
            'soundslice' => 'mstVc',
            'slices' => true,
            'signup' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/toto-hold-the-line.jpg',
            'artist' => 'Toto',
            'song' => "Hold The Line",
            'soundslice' => 't5bcc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/190995-card-thumbnail-maxres-1592340795.jpg',
            'artist' => 'Lenny Kravitz',
            'song' => "Always On The Run",
            'soundslice' => '162136',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/31532-card-thumbnail-maxres-1593723520.jpg',
            'artist' => 'CCR',
            'song' => "Proud Mary",
            'soundslice' => '162463',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/210724-card-thumbnail-maxres-1592416608.jpg',
            'artist' => 'Twenty One Pilots',
            'song' => "Car Radio",
            'soundslice' => '173091',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/queen-We-will-rock-you.jpg',
            'artist' => 'Queen',
            'song' => "We Will Rock You",
            'soundslice' => 'sHTfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/sting-fields-of-gold.jpg',
            'artist' => 'Sting',
            'song' => "Fields Of Gold",
            'soundslice' => 'tQFVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/system-of-a-down-toxicity.jpg',
            'artist' => 'System Of A Down',
            'song' => "Toxicity",
            'soundslice' => '162623',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/snow-patrol-chasing-cars.jpg',
            'artist' => 'Snow Patrol',
            'song' => "Chasing Cars",
            'soundslice' => 'Pw4fc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/296074-card-thumbnail-maxres-1616162037.jpg',
            'artist' => 'Tom Petty',
            'song' => "A Face In The Crowd",
            'soundslice' => 'nWkDc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/31234-card-thumbnail-maxres-1592341311.jpg',
            'artist' => 'Sublime',
            'song' => "Santeria",
            'soundslice' => '162471',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/the-beatles-come-together.jpg',
            'artist' => 'The Beatles',
            'song' => "Come Together",
            'soundslice' => '173467',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/otis-redding-sittin-on-the-dock-of-the-bay.jpg',
            'artist' => 'Otis Redding',
            'song' => "Sittin On The Dock Of The Bay",
            'soundslice' => '1zgVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/metallica-enter-sandman.jpg',
            'artist' => 'Metallica',
            'song' => "Enter Sandman",
            'soundslice' => '9ZnVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/red-hot-chili-peppers-give-it-away.jpg',
            'artist' => 'RHCP',
            'song' => "Give It Away",
            'soundslice' => '227104',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/260343-card-thumbnail-maxres-1592340469.jpg',
            'artist' => 'Coldplay',
            'song' => "Yellow",
            'soundslice' => 'NBLcc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2021-jan/album-art/Cyndi Lauper-Girls Just Want To Have Fun.jpg',
            'artist' => 'Cyndi Lauper',
            'song' => "Girls Just Wanna Have Fun",
            'soundslice' => '92Ffc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/264647-card-thumbnail-maxres-1623074401.jpg',
            'artist' => 'The Beatles',
            'song' => "A Hard Day's Night",
            'soundslice' => 'fmGVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/nitty-gritty-dirt-band-fishin-in-the-dark.jpg',
            'artist' => 'Nitty Gritty Dirt Band',
            'song' => "Fishin In The Dark",
            'soundslice' => '223969',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/billy-joel-dont-ask-me-why.jpg',
            'artist' => 'Billy Joel',
            'song' => "Don't Ask Me Why",
            'soundslice' => 'q4ffc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/coolio-gangstas-paradise.jpg',
            'artist' => 'Coolio',
            'song' => "Gangsta' Paradise",
            'soundslice' => 'xz4fc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/the-temptations-just-my-imagination.jpg',
            'artist' => 'The Temptations',
            'song' => "Just My Imagination",
            'soundslice' => 'Hw4fc',
            'slices' => true,
        ],
        [
            'image' => 'https://dzryyo1we6bm3.cloudfront.net/card-thumbnails/songs/550/drumeo-live-1715.jpg',
            'artist' => 'Bob Marley And The Wailers',
            'song' => "Could You Be Loved",
            'soundslice' => '162465',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/scorpions-rock-you-like-a-hurricane.jpg',
            'artist' => 'Scorpions',
            'song' => "Rock You Like A Hurricane",
            'soundslice' => '161933',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/298355-card-thumbnail-maxres-1617705611.jpg',
            'artist' => 'Brian Wilson',
            'song' => "Can't Wait Too Long",
            'soundslice' => 'F9RDc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/foo-fighters-everlong.jpg',
            'artist' => 'Foo Fighters',
            'song' => "Everlong",
            'soundslice' => '163125',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/metallica-master-of-puppets.jpg',
            'artist' => 'Metallica',
            'song' => "Master Of Puppets",
            'soundslice' => '169226',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/creedence-clearwater-revival-bad-moon-rising.jpg',
            'artist' => 'CCR',
            'song' => "Bad Moon Rising",
            'soundslice' => '4cffc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/rush-tom-sawyer.jpg',
            'artist' => 'Rush',
            'song' => "Tom Sawyer",
            'soundslice' => '169812',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/smashing-pumpkins-1979.jpg',
            'artist' => 'The Smashing Pumpkins',
            'song' => "1979",
            'soundslice' => 'jHTfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/green-day-american-idiot.jpg',
            'artist' => 'Green Day',
            'song' => "American Idiot",
            'soundslice' => '162895',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2021-jan/album-art/Lenny Kravitz-Low.jpg',
            'artist' => 'Lenny Kravitz',
            'song' => "Low",
            'soundslice' => 'H3Ffc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/13945-card-thumbnail-maxres-1592341257.jpg',
            'artist' => 'Radiohead',
            'song' => "Creep",
            'soundslice' => 'TkFVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/foo-fighters-monkey-wrench.jpg',
            'artist' => 'Foo Fighters',
            'song' => "Monkey Wrench",
            'soundslice' => '162635',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/bob-dylan-knocking-on-heavens-door.jpg',
            'artist' => 'Bob Dylan',
            'song' => "Knockin' On Heaven's Door",
            'soundslice' => '2XTfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-november/album-art/billy-ray-cyrus-achy-breaky-heart.jpg',
            'artist' => 'Billy Ray Cyrus',
            'song' => "Achy Breaky Heart",
            'soundslice' => 'YXTfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/mark-ronson-uptown-funk.jpg',
            'artist' => 'Bruno Mars',
            'song' => "Uptown Funk",
            'soundslice' => 'PZnVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/303356-card-thumbnail-maxres-1620991931.jpg',
            'artist' => 'Prince',
            'song' => "Forever In My Life",
            'soundslice' => 'JtBDc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/acdc-highway-to-hell.jpg',
            'artist' => 'AC/DC',
            'song' => "Highway To Hell",
            'soundslice' => 'brjcc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/the-white-stripes-seven-nation-army.jpg',
            'artist' => 'The White Stripes',
            'song' => "Seven Nation Army",
            'soundslice' => '7nmVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/green-day-boulevard-of-broken-dreams.jpg',
            'artist' => 'Green Day',
            'song' => "Boulevard Of Broken Dreams",
            'soundslice' => 'wnmVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/22855-card-thumbnail-maxres-1608066633.jpg',
            'artist' => 'Queens Of The Stone Age',
            'song' => "No One Knows",
            'soundslice' => '169787',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/journey-don_t-stop-believin.jpg',
            'artist' => 'Journey',
            'song' => "Don't Stop Believin'",
            'soundslice' => '163562',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/nirvana-come-as-you-are.jpg',
            'artist' => 'Nirvana',
            'song' => "Come As You Are",
            'soundslice' => 'rNSVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/20249-card-thumbnail-maxres-1592340937.jpeg',
            'artist' => 'Blink 182',
            'song' => "All The Small Things",
            'soundslice' => '169808',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/michael-jackson-billie-jean.jpg',
            'artist' => 'Michael Jackson',
            'song' => "Billie Jean",
            'soundslice' => 'Qhjcc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/maroon-5-sugar.jpg',
            'artist' => 'Maroon 5',
            'song' => "Sugar",
            'soundslice' => '162893',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/outkast-hey-ya.jpg',
            'artist' => 'Outkast',
            'song' => "Hey Ya!",
            'soundslice' => 'Sclfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/green-day-basket-case.jpg',
            'artist' => 'Green Day',
            'song' => "Basket Case",
            'soundslice' => '163274',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/snow-patrol-run.jpg',
            'artist' => 'Snow Patrol',
            'song' => "Run",
            'soundslice' => 'jw4fc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/294252-card-thumbnail-maxres-1614964266.jpg',
            'artist' => 'ZZ Top',
            'song' => "Gimme All Your Lovin'",
            'soundslice' => 'TmGVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/eminem-stan.png',
            'artist' => 'Eminem',
            'song' => "Stan",
            'soundslice' => '2z4fc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/the-police-roxanne.jpg',
            'artist' => 'The Police',
            'song' => "Roxanne",
            'soundslice' => '169625',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/28218-card-thumbnail-maxres-1592341146.jpg',
            'artist' => 'Aerosmith',
            'song' => "Walk This Way",
            'soundslice' => '162892',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/eagles-desperado.jpg',
            'artist' => 'Eagles',
            'song' => "Desperado",
            'soundslice' => '4nmVc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/pearl-jam-alive-1633697199.jpg',
            'artist' => 'Pearl Jam',
            'song' => "Even Flow",
            'soundslice' => '169230',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-september/album-art/tina-turner-whats-love-got-to-do-with-it.jpg',
            'artist' => 'Tina Turner',
            'song' => "What's Love Got To Do With It",
            'soundslice' => 'KVlfc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-july/album-art/creedence-clearwater-revival-green-river.jpg',
            'artist' => 'CCR',
            'song' => "Green River",
            'soundslice' => 'kcffc',
            'slices' => true,
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/wild-cherry-play-that-funky-music.jpg',
            'artist' => 'Wild Cherry',
            'song' => "Play That Funky Music",
            'soundslice' => '162480',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/drumeo-songs-2020-june/album-art/daft-punk-get-lucky.jpg',
            'artist' => 'Daft Punk',
            'song' => "Get Lucky",
            'soundslice' => '169801',
        ],
        [
            'image' => 'https://d1923uyy6spedc.cloudfront.net/red-hot-chili-peppers-otherside-1649337960.jpg',
            'artist' => 'Red Hot Chili Peppers',
            'song' => "Otherside",
            'soundslice' => 'ZVhMc',
            'slices' => true,
        ]
    ];
@endphp

<div class="album-grid flex flex-wrap justify-center">
    @foreach($bonuses as $bonus)
        @if(!empty($signup))
            @if(!empty($bonus['signup']))
                <div class="w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/5 px-2 md:px-3 mb-7 md:mb-10">
                    <div class="relative autoplay-video cursor-pointer overflow-hidden rounded-md" data-open="@if(!empty($dataOpen)){{$dataOpen}}@else{{str_replace(".","",(str_replace("/","",(str_replace(" ","",$bonus['artist'])))))}}{{$bonus['soundslice']}}@endif">
                        <i class="absolute top-1/2 left-1/2 fas fa-play play-button" style="margin: -39px;"></i>
                        <div class="aspect-1:1 w-full bg-contain bg-center lazyload" data-bg="https://cdn.musora.com/image/fetch/w_470,q_auto:best/{{ $bonus['image'] }}"></div>
                    </div>
                    <h5 class="mt-3 mb-1"><strong>{{ $bonus['artist'] }}</strong></h5>
                    <p class="leading-none">{{ $bonus['song'] }}</p>
                </div>
            @endif
        @else
            <div class="w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/5 px-2 md:px-3 mb-7 md:mb-10">
                <div class="relative autoplay-video cursor-pointer overflow-hidden rounded-md" data-open="@if(!empty($dataOpen)){{$dataOpen}}@else{{str_replace(".","",(str_replace("/","",(str_replace(" ","",$bonus['artist'])))))}}{{$bonus['soundslice']}}@endif">
                    <i class="absolute top-1/2 left-1/2 fas fa-play play-button" style="margin: -39px;"></i>
                    <div class="aspect-1:1 w-full bg-contain bg-center lazyload" data-bg="https://cdn.musora.com/image/fetch/w_470,q_auto:best/{{ $bonus['image'] }}"></div>
                </div>
                <h5 class="mt-3 mb-1"><strong>{{ $bonus['artist'] }}</strong></h5>
                <p class="leading-none">{{ $bonus['song'] }}</p>
            </div>

            <div class="reveal text-center" id="{{ str_replace(".","",(str_replace("/","",(str_replace(" ","",$bonus['artist']))))) }}{{$bonus['soundslice']}}" data-reveal>
                <div class="w-full relative overflow-hidden" style="padding-bottom: 85vh;">
                    <iframe class="fixed inset-0 h-full w-full absolute reset-on-close" frameborder="0" allowfullscreen="allowfullscreen" src=""
                            @if(!empty($bonus['slices']))
                            data-lazy-load-url="https://www.soundslice.com/slices/{{ $bonus['soundslice'] }}/embed/?api=1&amp;scroll_type=2&amp;branding=0"
                            @else
                            data-lazy-load-url="https://www.soundslice.com/scores/{{ $bonus['soundslice'] }}/embed/?api=1&amp;scroll_type=2&amp;branding=0"
                        @endif ></iframe>
                </div>
            </div>
        @endif
    @endforeach
</div>