<?php

return [
    // this gets updated on the fly in the SetLastUsedBrand middleware
    'brand' => 'musora',

    // customer.io
    // NOTE: you must add this queue to your queue worker setup, ex: artisan queue:work database --queue=customer_io
    'customer_io_queue_connection_name' => env('QUEUE_DRIVER', 'sync'),
    'customer_io_queue_name' => 'customer-io',

    'customer_io_brands_to_sync' => [
        'musora',
        'drumeo',
        'pianote',
        'guitareo',
        'singeo',
    ],

    // this gets updated on the fly in the SetLastUsedBrand middleware
    'customer_io_brand_activity_event' => 'musora',

    // only the brands set for a given customer.io account will have their info synced
    // see customer-io.php accounts config value
    'customer_io_account_name_brands_to_sync' => [
        'musora' => ['drumeo', 'pianote', 'guitareo', 'singeo', 'musora'],
        'drumeo' => ['drumeo',],
        'pianote' => ['pianote',],
        'guitareo' => ['guitareo',],
        'singeo' => ['singeo',],
    ],

    'customer_io_account_to_sync_all_brands' => 'musora',

    'customer_io_pack_skus_to_sync_ownership' => [
        '30-day-drummer',
        '30-day-drummer-2',
        'new-piano-players-start-here',
        'beyond-beginner-drumming',
        'festival-2020',
        'electrify-your-drumming',
        'four-weeks-to-better-drum-fills',
        'BDS2-DIGI',
        'BDS2-DIGIPHYS',
        'TDB-DIGI',
        'DFS-DIGI',
        'DFS-DIGIPHYS',
        'DPAS-DIGI',
        'DPAS-DIGIPHYS',
        'DRUDSYS-DIGIPHYS',
        'DRUDSYS-DIGI',
        'DTUNESYS-DIGIPHYS',
        'DTUNESYS-DIGI',
        'DSYS2-DIGI',
        'DSYS2-DIGIPHYS',
        'JDS-DIGI',
        'JDS-DIGIPHYS',
        'LDS-DIGI',
        'LDS-DIGIPHYS',
        'MOELLERMS-DIGI',
        'MOELLERMS-DIGIPHYS',
        'SD-DIGI',
        'SD-DIGIPHYS',
        'TCM-DIGI',
        'TCM-DIGIPHYS',
        'MM-DIGIPHYS',
        'MM-DIGI',
        'MASTERCLASS-TRJ',
        'DLM-teachers-training-pack',
        'independence-made-easy',
        'independence-made-easy-july-2017',
        'drum-technique-made-easy',
        'independence-made-easy-july-2018',
        'AOADS-DIGI',
        'BTC-DIGI',
        'CC-DIGI',
        'GHFAL-DIGI',
        'HGAF-DIGI',
        'ICM-DIGI',
        'MAM-DIGI',
        'SWFTMD-DIGI',
        'TG-DIGI',
        'TLOD-DIGI',
        'rock-drumming-masterclass',
        'drum-technique-made-easy-april-2019-semester',
        'rock-drumming-masterclass-july-2019-semester',
        'rock-drumming-system',
        'drum-gear-buyers-guide',
        'new-drummers-start-here',
        'learn-songs-faster-pack',
        'independence-made-easy-pack',
        'rock-drumming-masterclass-pack',
        'drum-technique-made-easy-pack',
    ],

    'customer_io_pack_sku_to_purchase_event_name' => [
        'BDS2-DIGI' => 'bass-drum-secrets',
        'BDS2-DIGIPHYS' => 'bass-drum-secrets',
        'TCM-DIGI' => 'cobus-method',
        'TCM-DIGIPHYS' => 'cobus-method',
        'DLM-teachers-training-pack' => 'dft',
        'DFS-DIGI' => 'drum-fill-system',
        'DFS-DIGIPHYS' => 'drum-fill-system',
        'DRUDSYS-DIGIPHYS' => 'drum-rudiment-system',
        'DRUDSYS-DIGI' => 'drum-rudiment-system',
        'drum-technique-made-easy-april-2019-semester' => 'drum-technique-made-easy_apr-2019',
        'drum-technique-made-easy' => 'drum-technique-made-easy_jan-2018',
        'drum-technique-made-easy_jul-2018' => 'drum-technique-made-easy-pack',
        'DTUNESYS-DIGIPHYS' => 'drum-tuning-system',
        'DTUNESYS-DIGI' => 'drum-tuning-system',
        'TDB-DIGI' => 'drumming-blueprint',
        'DSYS2-DIGI' => 'drumming-system-2',
        'DSYS2-DIGIPHYS' => 'drumming-system-2',
        'electrify-your-drumming' => 'electrify-your-drumming',
        'festival-2020' => 'festival-2020',
        'drum-gear-buyers-guide' => 'gear-buyers-guide',
        'AOADS-DIGI' => 'hudson_anatomy-of-a-drum-solo',
        'BTC-DIGI' => 'hudson_beyond-the-chops',
        'CC-DIGI' => 'hudson_creative-control',
        'GHFAL-DIGI' => 'hudson_great-hands-for-a-lifetime',
        'HGAF-DIGI' => 'hudson_grooves-and-fills',
        'ICM-DIGI' => 'hudson_constant-motion',
        'MAM-DIGI' => 'hudson_methods-and-mechanics',
        'TG-DIGI' => 'hudson_the-grid',
        'TLOD-DIGI' => 'hudson_the-language-of-drumming',
        'independence-made-easy' => 'independance-made-easy_jan-2017',
        'independence-made-easy-july-2017' => 'independance-made-easy_jul-2017',
        'JDS-DIGI' => 'jazz-drumming-system',
        'JDS-DIGIPHYS' => 'jazz-drumming-system',
        'LDS-DIGI' => 'latin-drumming-system',
        'LDS-DIGIPHYS' => 'latin-drumming-system',
        'MM-DIGIPHYS' => 'maximum-meytal',
        'MM-DIGI' => 'maximum-meytal',
        'MOELLERMS-DIGI' => 'moeller-method',
        'MOELLERMS-DIGIPHYS' => 'moeller-method',
        'rock-drumming-masterclass' => 'rock-drumming-masterclass_jan-2019',
        'rock-drumming-masterclass-july-2019-semester' => 'rock-drumming-masterclass_jul-2019',
        'rock-drumming-system' => 'rock-drumming-system',
        'SD-DIGI' => 'successful-drumming',
        'SD-DIGIPHYS' => 'successful-drumming',
        'MASTERCLASS-TRJ' => 'trj-masterclass',
        'beyond-beginner-drumming' => 'beyond-beginner-drumming',
        '30-day-drummer' => '30-day-drummer',
    ],

    'customer_io_content_type_to_event_string_map' => [
        'course' => 'course',
        'learning-path' => 'learning-path',
        'learning-path-course' => 'learning-path_course',
        'learning-path-lesson' => 'learning-path_lesson',
        'unit' => 'learning-path',
        'play-along' => 'play-along',
        'song' => 'song',
        'pack' => 'pack',
        'semester-pack' => 'pack',
        'semester-pack-lesson' => 'pack',
        'pack-bundle-lesson' => 'pack-bundle-lesson',
        'coach-stream' => 'coach_lesson',
        'rudiment' => 'rudiment',
        'show' => 'show',
        '25-days-of-christmas' => 'show',
        'behind-the-scenes' => 'show',
        'boot-camps' => 'show',
        'camp-drumeo-ah' => 'show',
        'challenges' => 'show',
        'diy-drum-experiments' => 'show',
        'exploring-beats' => 'show',
        'gear-guides' => 'show',
        'ha-oemurd-pmac' => 'show',
        'in-rhythm' => 'show',
        'live' => 'show',
        'namm-2019' => 'show',
        'on-the-road' => 'show',
        'paiste-cymbals' => 'show',
        'performances' => 'show',
        'podcasts' => 'show',
        'question-and-answer' => 'show',
        'quick-tips' => 'show',
        'recording' => 'show',
        'rhythmic-adventures-of-captain-carson' => 'show',
        'rhythms-from-another-planet' => 'show',
        'solos' => 'show',
        'sonor-drums' => 'show',
        'student-collaborations' => 'show',
        'student-focus' => 'show',
        'student-review' => 'show',
        'study-the-greats' => 'show',
        'tama-drums' => 'show',
    ],

    // if the users subscription is a trial, the attribute 'brand_membership_subscription_trial-type' will be set based on this
    'customer_io_trial_product_sku_to_type' => [
        'drumeo' => [
            'DLM-Trial-30-Day' => 'monthly_30_days_free',
            'DLM-Trial-1-month' => 'monthly_7_days_free',
            'DLM-Trial-Annual-30-Day' => 'annual_30_days_free',
            'DLM-Trial-Annual-7-Day' => 'annual_7_days_free',
        ],
    ],

    // helpscout
    'helpscout_queue_connection_name' => env('QUEUE_DRIVER', 'sync'),
    'helpscout_queue_name' => 'helpscout',
    'help_scout_sync_brands' => ['drumeo', 'pianote', 'guitareo', 'singeo'],

    // ecommerce -> content permissions
    'ecommerce_product_sku_to_content_permission_name_map' => [

        // guitareo
        'GUITAREO-1-MONTH-MEMBERSHIP' => 'Guitareo Membership',
        'GUITAREO-1-YEAR-MEMBERSHIP-ACCESS' => 'Guitareo Membership',
        'GUITAREO-1-YEAR-MEMBERSHIP' => 'Guitareo Membership',
        'GUITAREO-6-MONTH-MEMBERSHIP' => 'Guitareo Membership',
        'GUITAREO-6-MONTH-ACCESS' => 'Guitareo Membership',
        'GUITAREO-1-DOLLAR-1-MONTH-ACCESS' => 'Guitareo Membership',
        'GUITAREO-LIFETIME-MEMBERSHIP' => 'Guitareo Membership',
        'GUITAREO-7-DAY-TRIAL-ONE-TIME' => 'Guitareo Membership',
        'GTME-JAN-2018-SEMESTER' => 'Guitar Technique Made Easy',
        'GTME-JUL-2018-SEMESTER' => 'Guitar Technique Made Easy - July 2018 Semester',
        'GTME-OCT-2018-SEMESTER' => 'Guitar Technique Made Easy - October 2018 Semester',
        'AGME-JAN-2019-SEMESTER' => 'Acoustic Guitar Made Easy - January 2019 Semester',
        'AGME-MAY-2019-SEMESTER' => 'Acoustic Guitar Made Easy - May 2019 Semester',
        'guitar-quest' => 'Guitar Quest',

        // pianote
        'destupefy-your-left-hand' => 'De-Stupefy Your Left Hand',
        'piano-technique-made-easy' => 'Piano Technique Made Easy',
        '500-songs-in-5-days' => '500 Songs In 5 Days',
        '500-songs-in-5-days-99' => '500 Songs In 5 Days',
        'sight-reading-made-simple' => 'Sight Reading Made Simple',
        '500-songs-in-5-days-guitareo' => '500 Songs In 5 Days',
        'faster-fingers' => 'Faster Fingers',
        'GUITAR-SYSTEM' => 'Guitar System',
        'piano-riffs-and-fills' => 'Piano Riffs & Fills',
        'worship-piano' => 'Worship Piano',

        // drumeo
        '30-day-drummer' => '30 Day Drummer',
        'beyond-beginner-drumming' => 'Beyond Beginner Drumming',
        'new-drummers-start-here' => 'New Drummers Start Here',
        'electrify-your-drumming' => 'Electrify Your Drumming',
        'festival-2020' => 'Drumeo Festival 2020',
        'four-weeks-to-better-drum-fills' => '4 Weeks To Better Drum Fills',
        'BDS2-DIGI' => 'Bass Drum Secrets',
        'BDS2-DIGIPHYS' => 'Bass Drum Secrets',
        'DFS-DIGI' => 'Drum Fill System',
        'DFS-DIGIPHYS' => 'Drum Fill System',
        'DPAS-DIGI' => 'Drum Play-Along System',
        'DPAS-DIGIPHYS' => 'Drum Play-Along System',
        'DRUDSYS-DIGIPHYS' => 'Drum Rudiment System',
        'DRUDSYS-DIGI' => 'Drum Rudiment System',
        'DTUNESYS-DIGIPHYS' => 'Drum Tuning System',
        'DTUNESYS-DIGI' => 'Drum Tuning System',
        'DSYS2-DIGI' => 'Drumming System 2.0',
        'DSYS2-DIGIPHYS' => 'Drumming System 2.0',
        'JDS-DIGI' => 'Jazz Drumming System',
        'JDS-DIGIPHYS' => 'Jazz Drumming System',
        'LDS-DIGI' => 'Latin Drumming System',
        'LDS-DIGIPHYS' => 'Latin Drumming System',
        'MOELLERMS-DIGI' => 'Moeller Method Secrets',
        'MOELLERMS-DIGIPHYS' => 'Moeller Method Secrets',
        'SD-DIGI' => 'Successful Drumming',
        'SD-DIGIPHYS' => 'Successful Drumming',
        'TCM-DIGI' => 'Cobus Method',
        'TCM-DIGIPHYS' => 'Cobus Method',
        'MM-DIGIPHYS' => 'Maximum Meytal',
        'MM-DIGI' => 'Maximum Meytal',
        'MASTERCLASS-TRJ' => 'Tony Royster Jr. Masterclass',
        'DLM-1-month' => 'Drumeo Edge',
        'DLM-1-year' => 'Drumeo Edge',
        'DLM-Trial-1-month' => 'Drumeo Edge',
        'DLM-Trial-Annual-7-Day' => 'Drumeo Edge',
        'DLM-Trial-Annual-30-Day' => 'Drumeo Edge',
        'DLM-Trial-30-Day' => 'Drumeo Edge',
        'DLM-6-month' => 'Drumeo Edge',
        'DLM-teachers-1-year' => 'Drumeo for Teachers',
        'DLM-teachers-upgrade-1-month' => 'Drumeo for Teachers',
        'DLM-teachers-upgrade-1-year' => 'Drumeo for Teachers',
        'DLM-3-month' => 'Drumeo Edge',
        'DLM-UPSELL-2-month' => 'Drumeo Edge',
        'DLM-Lifetime' => 'Drumeo Edge',
        'gsotd-bundle' => 'Getting Started On The Drums',
        'rbaf-bundle' => 'Rock Beats & Fills',
        'bdt-bundle' => 'Bass Drum Technique',
        'fd-bundle' => 'Funky Drumming',
        'myg-bundle' => 'Maximize Your Groove',
        'rd-bundle' => 'Recording Drums',
        'independence-made-easy' => 'Independence Made Easy - January 2017 Semester',
        'independence-made-easy-july-2017' => 'Independence Made Easy - July 2017 Semester',
        'drum-technique-made-easy' => 'Drum Technique Made Easy',
        'DLM-1-month-promo' => 'Drumeo Edge',
        'independence-made-easy-july-2018' => 'Independence Made Easy - July 2018 Semester',
        'AOADS-DIGI' => 'Anatomy Of A Drum Solo',
        'BTC-DIGI' => 'Beyond The Chops',
        'CC-DIGI' => 'Creative Control',
        'GHFAL-DIGI' => 'Great Hands For A Lifetime',
        'HGAF-DIGI' => 'Hands, Grooves & Fills',
        'ICM-DIGI' => 'In Constant Motion',
        'MAM-DIGI' => 'Methods & Mechanics',
        'TG-DIGI' => 'The Grid: A System For Creative Drumming and Improvisation',
        'TLOD-DIGI' => 'The Language Of Drumming',
        'rock-drumming-masterclass' => 'Rock Drumming Masterclass - January 2019 Semester',
        'drum-technique-made-easy-april-2019-semester' => 'Drum Technique Made Easy - April 2019 Semester',
        'DLM-Trial-Best-Book-1-month' => 'Drumeo Edge',
        'rock-drumming-masterclass-july-2019-semester' => 'Rock Drumming Masterclass - July 2019 Semester',
        'edge-membership-6-months' => 'Drumeo Edge',
        'drumeo_edge_30_days_access' => 'Drumeo Edge',
        'drumeo_access_30-days' => 'Drumeo Edge',
        'drumeo_edge_1_year_access' => 'Drumeo Edge',
        'drumeo_access_90-days' => 'Drumeo Edge',

        'learn-songs-faster-pack' => 'Learn Songs Faster',
        'independence-made-easy-pack' => 'Independence Made Easy - Pack',
        'rock-drumming-masterclass-pack' => 'Rock Drumming Masterclass - Pack',
        'drum-technique-made-easy-pack' => 'Drum Technique Made Easy - Pack',

        // singeo
        'singeo-annual-recurring-30-day-trial-membership' => 'Singeo Membership',
        'singeo-monthly-recurring-30-day-trial-membership' => 'Singeo Membership',
        'singeo-lifetime-membership-access' => 'Singeo Membership',
        'singeo-1-year-membership-access' => 'Singeo Membership',
        'singeo-annual-recurring-membership' => 'Singeo Membership',
        'singeo-monthly-recurring-membership' => 'Singeo Membership',

        // recordeo
        'TUGTRD-PACK' => 'The Ultimate Guide To Recording Drums',
        'TUGTRG-PACK' => 'The Ultimate Guide To Recording Guitar',
        'MEMBERSHIP-1-YEAR' => 'Recordeo Membership',
        'MEMBERSHIP-1-MONTH' => 'Recordeo Membership',
    ],

    // membership product skus
    'pianote_membership_product_skus' => [
        'PIANOTE-MEMBERSHIP-1-MONTH',
        'PIANOTE-MEMBERSHIP-1-YEAR',
        'PIANOTE-MEMBERSHIP-LIFETIME',
        'PIANOTE-MEMBERSHIP-LIFETIME-EXISTING-MEMBERS',
        '1-DOLLAR',
        'PIANOTE-MEMBERSHIP-6-MONTH',
        'PIANOTE-MEMBERSHIP-TRIAL',
        'PIANOTE-MEMBERSHIP-TRIAL-30-DAY',
        'PIANOTE-MEMBERSHIP-TRIAL-30-DAY-ANNUAL',
        'PIANOTE-MEMBERSHIP-TRIAL-7-DAY-ANNUAL',
        'pianote_membership_90_days_access',
        'PIANOTE-1-YEAR-MEMBERSHIP-ACCESS',
    ],
    'guitareo_membership_product_skus' => [
        'GUITAREO-1-MONTH-MEMBERSHIP',
        'GUITAREO-1-YEAR-MEMBERSHIP',
        'GUITAREO-6-MONTH-MEMBERSHIP',
        'GUITAREO-1-DOLLAR-1-MONTH-ACCESS',
        'GUITAREO-6-MONTH-ACCESS',
        'GUITAREO-LIFETIME-MEMBERSHIP',
        'GUITAREO-7-DAY-TRIAL-ONE-TIME',
        'GUITAREO-1-YEAR-MEMBERSHIP-ACCESS',
    ],
    'drumeo_membership_product_skus' => [
        'DLM-1-month',
        'DLM-1-year',
        'DLM-Trial-1-month',
        'DLM-Trial-Annual-30-Day',
        'DLM-Trial-Annual-7-Day',
        'DLM-6-month',
        'DLM-teachers-1-year',
        'DLM-teachers-upgrade-1-month',
        'DLM-teachers-upgrade-1-year',
        'DLM-3-month',
        'DFT-PASS-1_old-1-month',
        'DLM-UPSELL-2-month',
        'DLM-Trial-Best-Book-1-month',
        'DLM-Trial-Drummers-Toolbox-1-month',
        'DLM-Lifetime',
        'drumeo_edge_30_days_access',
        'drumeo_access_30-days',
        'drumeo_edge_1_year_access',
        'drumeo_access_90-days',
        'DLM-Trial-30-Day',
    ],
    'singeo_membership_product_skus' => [
        'singeo-annual-recurring-30-day-trial-membership',
        'singeo-monthly-recurring-30-day-trial-membership',
        'singeo-lifetime-membership-access',
        'singeo-1-year-membership-access',
        'singeo-annual-recurring-membership',
        'singeo-monthly-recurring-membership',
    ],

    'pack_ecommerce_product_sku_to_content_slug' => [
        '30-day-drummer' => '30-day-drummer',
        'beyond-beginner-drumming' => 'beyond-beginner-drumming',
        'new-drummers-start-here' => 'new-drummers-start-here',
        'electrify-your-drumming' => 'electrify-your-drumming',
        'festival-2020' => 'drumeo-festival-2020-video-pack',
        'four-weeks-to-better-drum-fills' => '4-weeks-to-better-drum-fills',
        'BDS2-DIGI' => 'bass-drum-secrets',
        'BDS2-DIGIPHYS' => 'bass-drum-secrets',
        'DFS-DIGI' => 'drum-fill-system',
        'DFS-DIGIPHYS' => 'drum-fill-system',
        'DPAS-DIGI' => 'drum-play-along-system',
        'DPAS-DIGIPHYS' => 'drum-play-along-system',
        'DRUDSYS-DIGIPHYS' => 'drum-rudiment-system',
        'DRUDSYS-DIGI' => 'drum-rudiment-system',
        'DTUNESYS-DIGIPHYS' => 'drum-tuning-system',
        'DTUNESYS-DIGI' => 'drum-tuning-system',
        'DSYS2-DIGIPHYS' => 'drumming-system-2',
        'DSYS2-DIGI' => 'drumming-system-2',
        'JDS-DIGI' => 'jazz-drumming-system',
        'JDS-DIGIPHYS' => 'jazz-drumming-system',
        'LDS-DIGI' => 'latin-drumming-system',
        'LDS-DIGIPHYS' => 'latin-drumming-system',
        'MOELLERMS-DIGI' => 'moeller-method-secrets',
        'MOELLERMS-DIGIPHYS' => 'moeller-method-secrets',
        'SD-DIGIPHYS' => 'successful-drumming',
        'SD-DIGI' => 'successful-drumming',
        'TCM-DIGI' => 'cobus-method',
        'TCM-DIGIPHYS' => 'cobus-method',
        'MM-DIGIPHYS' => 'maximum-meytal',
        'MM-DIGI' => 'maximum-meytal',
        'MASTERCLASS-TRJ' => 'tony-royster-jr-masterclass',
        'DLM-teachers-training-pack' => 'drumeo-for-teachers',
        'independence-made-easy' => 'independence-made-easy',
        'independence-made-easy-july-2017' => 'independence-made-easy-july-2017-semester',
        'drum-technique-made-easy' => 'drum-technique-made-easy',
        'independence-made-easy-july-2018' => 'independence-made-easy-july-2018-semester',
        'AOADS-DIGI' => 'anatomy-of-a-drum-solo',
        'BTC-DIGI' => 'beyond-the-chops',
        'CC-DIGI' => 'creative-control',
        'GHFAL-DIGI' => 'great-hands-for-a-lifetime',
        'HGAF-DIGI' => 'hands-grooves-fills',
        'ICM-DIGI' => 'in-constant-motion',
        'MAM-DIGI' => 'methods-mechanics',
        'TG-DIGI' => 'the-grid-a-system-for-creative-drumming-and-improvisation',
        'TLOD-DIGI' => 'the-language-of-drumming',
        'rock-drumming-masterclass' => 'rock-drumming-masterclass-january-2019-semester',
        'drum-technique-made-easy-april-2019-semester' => 'drum-technique-made-easy-april-2019-semester',
        'rock-drumming-masterclass-july-2019-semester' => 'rock-drumming-masterclass-july-2019-semester',
        'rock-drumming-system' => 'rock-drumming-system',
        'drum-gear-buyers-guide' => 'drum-gear-buyers-guide',

        'learn-songs-faster-pack' => 'learn-songs-faster',
        'independence-made-easy-pack' => 'independence-made-easy-pack',
        'rock-drumming-masterclass-pack' => 'rock-drumming-masterclass-pack',
        'drum-technique-made-easy-pack' => 'drum-technique-made-easy-pack',
    ],

    // impact railanalytics
    // NOTE: this is currently not used
    'impact_queue_connection_name' => env('QUEUE_DRIVER', 'sync'),
    'impact_queue_name' => 'impact',

    // sasquatch integration
    'customer_io_saasquatch_email_invite_event_name' => '_saasquatch_referral-link_30-day',
    'customer_io_saasquatch_email_invite_link_attribute_name' => '_saasquatch_referral-link_30-day',
];
