<?php

$bonuses = [
    [
        'imageFull' => true,
        'image' => 'https://www.musora.com/musora-cdn/image/width=520,quality=95/https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/marketing/drumeo/promos/november/2024/bonus-30dd.webp',
        'title' => '30-Day Drummer',
        'description' => 'Learn the drums with daily guided workouts.',
        'sku' => '30-day-drummer-4',
    ],
    [
        'imageFull' => true,
        'image' => 'https://www.musora.com/musora-cdn/image/width=520,quality=95/https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/marketing/drumeo/promos/november/2024/bonus-30di.webp',
        'title' => '30-Day Independence',
        'description' => 'Improve your coordination with daily guided workouts.',
        'sku' => '30-day-independence',
    ],
    [
        'imageFull' => true,
        'image' => 'https://www.musora.com/musora-cdn/image/width=520,quality=95/https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/marketing/drumeo/promos/november/2024/bonus-30ddb.webp',
        'title' => '30-Day Double Bass',
        'description' => 'Unlock your foot speed & control on the drums.',
        'sku' => '30-day-double-bass',
    ],
    [
        'imageFull' => true,
        'image' => 'https://www.musora.com/musora-cdn/image/width=520,quality=95/https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/marketing/drumeo/promos/november/2024/bonus-30dj.webp',
        'title' => '30-Day Jazz',
        'description' => 'Immerse yourself in jazz drumming for 30 days.',
        'sku' => '30-day-jazz',
    ],
    [
        'imageFull' => true,
        'image' => 'https://www.musora.com/musora-cdn/image/width=520,quality=95/https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/marketing/drumeo/promos/november/2024/bonus-30dc.webp',
        'title' => '30-Day Chops',
        'description' => 'Boost your creativity in just 30 days',
        'sku' => '30-day-chops',
    ],
    [
        'image' => 'https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/filters:quality(95)/marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-07.webp',
        'title' => 'Drumeo EarDrums',
        'description' => 'Drumeo EarDrums reduce external volume by up to -29dB. That means you can play hard while protecting your ears.',
        'sku' => 'drumeo-eardrums',
        'online-ship' => "Free Shipping",
        'shipping' => "no-shipping",
        'sku' => 'drumeo-eardrums',
    ],
    [
        'image' => 'https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/filters:quality(95)/marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-15.webp',
        'title' => 'Drumeo QuietKick',
        'description' => 'Improve your kick foot anywhere with the portable & quiet bass drum workout pad. Attaches to any single OR double pedal (pedal not included).',
        'sku' => 'quietkick',
        'online-ship' => "Free Shipping",
        'shipping' => true,
        'sku' => 'quietkick',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/pad.jpg',
        'title' => 'QuietPad',
        'description' => 'Practice anywhere with two full-size playing surfaces.',
        'sku' => 'quietpad',
        'shipping' => true,
        'sku' => 'quietpad',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/p4.jpg',
        'title' => 'Practice Pad',
        'description' => 'The most versatile practice pad in the world, featuring four playing surfaces on three different levels for simulating movement around the kit.',
        'sku' => 'practicepad',
        'shipping' => true,
        'sku' => 'practicepad',
    ],
    [
        'image' => 'https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/filters:quality(95)/marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-09.webp',
        'title' => 'The Best Beginner Drum Book',
        'description' => '',
        'sku' => 'BeginnerBook',
        'shipping' => true,
        'sku' => 'BeginnerBook',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/drumsticks.jpg',
        'title' => 'Drumeo Drumsticks',
        'description' => 'Drumeo 5A Drumsticks by Vater — made with hickory and extra moisture to last longer.',
        'sku' => 'Drumeo-VaterSticks',
        'shipping' => true,
        'sku' => 'Drumeo-VaterSticks',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/rdm.jpg',
        'title' => 'Rock Drumming Masterclass',
        'description' => 'Todd Sucherman’s 26-week masterclass to help you improve your rock drumming.',
        'sku' => 'rock-drumming-masterclass-pack',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/dtme.jpg',
        'title' => 'Drum Technique Made Easy',
        'description' => 'Bruce Becker’s 26-week masterclass to improve your hand & foot technique.',
        'sku' => 'drum-technique-made-easy-pack',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/ime.jpg',
        'title' => 'Independence Made Easy',
        'description' => 'Jared Falk’s 26-week masterclass to unlock your musicality and freedom on the drums.',
        'sku' => 'independence-made-easy-pack',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/eyd.jpg',
        'title' => 'Electrify Your Drumming',
        'description' => 'Your guide to playing 10 styles of electronic dance music - includes 23 play-alongs!',
        'sku' => 'electrify-your-drumming',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/sd.jpg',
        'title' => 'Successful Drumming',
        'description' => 'Jared Falk’s step-by-step curriculum for building a rock-solid foundation on the drums.',
        'sku' => 'SD-DIGI',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/fwtbdf.jpg',
        'title' => 'Better Drum Fills',
        'description' => 'The ultimate four-week crash course to playing more creative & musical drum fills.',
        'sku' => 'four-weeks-to-better-drum-fills',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/lsf.jpg',
        'title' => 'Learn Songs Faster',
        'description' => 'This masterclass will give you proven techniques for learning MORE songs in less time.',
        'sku' => 'learn-songs-faster-pack',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/july/tommy_card.jpg',
        'title' => 'Great Hands For A Lifetime',
        'description' => 'Tommy Igoe helps you improve your hand strength, speed, stamina, comfort, and control in the drums in four hours of video lessons.',
        'sku' => 'GHFAL-DIGI',
    ],
    [
        'image' => 'https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/filters:quality(95)/marketing/drumeo/promos/november/2024/bonuses-new/nitro-max.webp',
        'title' => 'Alesis Nitro Max E-Kit',
        'description' => 'Transform your room, apartment or townhouse into a drum studio.',
        'price' => 1065.00,
        'shipping' => true,
        'sku' => 'alesis-nitro-max-e-kit',
    ],
    [
        'imageFull' => true,
        'image' => 'https://d21q7xesnoiieh.cloudfront.net/fit-in/600x0/filters:quality(95)/marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-02.webp',
        'title' => '30-Day Independence',
        'description' => 'Independence is the hardest part of learning the drums.',
        'price' => 127.00,
        'sku' => '30-day-independence',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-13.webp',
        'title' => 'Drumeo PadStand',
        'description' => 'Practice anywhere with perfect height and ergonomics.',
        'price' => 79.00,
        'shipping' => true,
        'sku' => 'padstand',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-08.webp',
        'title' => 'Drumeo Headphones',
        'description' => 'Studio-Quality Sound. The Drumeo Headphones deliver studio-quality sound, all-day comfort, and improved low-end for E-Kit bass frequencies.',
        'price' => 99.00,
        'shipping' => true,
        'sku' => 'headphones',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-10.webp',
        'title' => 'Easy Rudiments Book',
        'description' => 'The 15 Rudiments You Actually Need To Know (And How To Learn Them Quickly).',
        'price' => 29.99,
        'shipping' => true,
        'sku' => 'easy-rudiments-book',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-11.webp',
        'title' => 'The Drummer\'s Toolbox Book',
        'description' => 'The Drummer\'s Toolbox presents drummers of all skill levels with the most comprehensive introduction to 101 drumming styles from the past century.',
        'price' => 29.99,
        'shipping' => true,
        'sku' => 'the-drummers-toolbox-book',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-14.webp',
        'title' => '2 Pairs Of Drumsticks',
        'description' => 'Our new Drumeo 5A Drumsticks by Vater – made of hickory for strength and durability.',
        'price' => 25.90,
        'shipping' => true,
        'sku' => 'Drumeo-VaterSticks-2',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-14.webp',
        'title' => 'Pair Of Drumsticks',
        'description' => 'Our new Drumeo 5A Drumsticks by Vater – made of hickory for strength and durability.',
        'price' => 25.90,
        'shipping' => true,
        'sku' => 'Drumeo-VaterSticks',
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-03.webp',
        'title' => '30-Day Double Bass',
        'description' => 'Learn double bass speed, endurance and coordination with daily guided workouts.',
        'price' => 127.00,
        'sku' => '30-day-double-bass'
    ],
    [
        'image' => 'marketing/drumeo/promos/november/2024/bonuses-bottom/bonus-04.webp',
        'title' => '30-Day Jazz',
        'description' => 'In 30-Day Jazz, you\'ll be introduced to the grooves, fills and techniques you need to play along with iconic jazz songs.',
        'price' => 127.00,
        'sku' => '30-day-jazz'
    ],
];
