@extends('drumeo._partials.global-layout')

@section('global-head')
    <title>Privacy Policy | Drumeo</title>
    <meta property="og:title" content="Privacy Policy">
    <meta name="description" content="Below is a list of the standard policies we use on this website.">

    @include('drumeo._partials._fonts')

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"/>
    <link href="{{ asset('/marketing/parcel/drumeo/navigation-sales.css') }}" rel="stylesheet">

    <style>
        h1, h2, h3, p {
            font-family:"Open Sans", sans-serif;
        }
    </style>
@stop

@section('global-body')
    @include("drumeo.sales.partials._nav", [
            "subscriptionVersion" => true
        ])

    <div class="hero-header px-4 py-12 md:py-20 lg:py-32 bg-black bg-center bg-cover" style="background-image:url(https://dpwjbsxqtam5n.cloudfront.net/sales/sub-options-bg.jpg);">
        <div class="container mx-auto">
            <h1 class="mx-auto text-center text-white text-2xl md:text-4xl font-bold">Privacy Policy</h1>
            <p class="text-sm text-center text-white opacity-75"><em>Last updated: September 2020</em></p>
        </div>
    </div>
    <div class="container mx-auto py-12 px-3 md:px-4">
        <p class="py-2">Musora Media Inc., (&ldquo;Company&rdquo;,&rdquo; us", "we", or "our") operates the drumeo.com, pianote.com, and guitareo.com website (the "Service").</p>
        <p class="py-2">This page informs you of our policies regarding the collection, use, and disclosure of personal data when you elect to use our Service, along with the choices you have associated with that data. </p>
        <p class="py-2">We use your and others&rsquo; data to provide and improve the Service. By using the Service, you agree to our collection and use of information as described in this policy. In order for us to improve the Service, we rely on the collection and use of this information. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <a href="/terms" class="text-blue-600">here</a>.</p>
        <h1 class="font-bold md:text-2xl mt-10 mb-4">Definitions</h1>
        <h3 class="font-bold md:text-lg mt-10">Personal Data</h3>
        <p class="py-2">Personal Data means data about a natural, living person who may be identified from such data (or from those and other information either in our possession or likely to come into our possession).</p>
        <h3 class="font-bold md:text-lg mt-10">Usage Data</h3>
        <p class="py-2">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit, browser identification, etc).</p>
        <h3 class="font-bold md:text-lg mt-10">Cookies</h3>
        <p class="py-2">Cookies are small amounts of data stored on a User&rsquo;s device when he or she visits certain websites.</p>
        <h3 class="font-bold md:text-lg mt-10">Data Controller</h3>
        <p class="py-2">Data Controller means a person who (either alone or jointly or in common with other persons) determines whether and how any personal data are processed, and the purposes of such processing.</p>
        <p class="py-2">For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
        <h3 class="font-bold md:text-lg mt-10">Data Processor (or Service Providers)</h3>
        <p class="py-2">Data Processor (or Service Provider) means any company or person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller.</p>
        <p class="py-2">We use various Service Providers in order to process your data more effectively. </p>
        <h3 class="font-bold md:text-lg mt-10">Data Subject</h3>
        <p class="py-2">A Data Subject is any living individual who is the subject of Personal Data.</p>
        <h3 class="font-bold md:text-lg mt-10">User</h3>
        <p class="py-2">A User is the individual who uses our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
        <h1 class="font-bold md:text-2xl mt-10 mb-4">Information Collection and Use</h1>
        <p class="py-2">We collect different types of information for various purposes to provide and improve our Service to you.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Types of Data Collected</h2>
        <h4 class="font-bold md:text-lg mt-10">Personal Data</h4>
        <p class="py-2">While using our Service, we may ask you to provide us with certain personally identifiable information that may be used to contact or identify you ("Personal Data"). Users can provide Personal Data not only for us, but for other members in the community across any and all of our Services. Personally, identifiable information may include, but is not limited to:</p>
        <ul class="list-disc ml-10 py-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Gender</li>
            <li>Avatar photo</li>
            <li>Birthday</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Other biographical information</li>
            <li>Cookies and Usage Data</li>
            <li>Music equipment preferences</li>
        </ul>
        <p class="py-2">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt-out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>
        <p class="py-2">We also collect certain Personal Data from users who are accessing our Services through websites under our control offering free lessons. This Personal Data is subject to the same terms and conditions in this Privacy Policy. </p>
        <h4 class="font-bold md:text-lg mt-10">Usage Data</h4>
        <p class="py-2">We may also collect information regarding how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, any linked devices that you may own that use our Services, purchase history, geographic location, unique device identifiers and other diagnostic data.</p>
        <h4 class="font-bold md:text-lg mt-10">Tracking Cookies Data</h4>
        <p class="py-2">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
        <p class="py-2">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
        <p class="py-2">You may instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
        <p class="py-2">Examples of Cookies we use:</p>
        <ul class="list-disc ml-10 py-2">
            <li>Session Cookies. We use Session Cookies to operate our Service.</li>
            <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
            <li>Security Cookies. We use Security Cookies for security purposes.</li>
            <li>Authentication Cookies. We use Authentication Cookies for members within our platforms.</li>
        </ul>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Use of Data</h2>
        <p class="py-2">Company uses the collected data for various purposes:</p>
        <ul class="list-disc ml-10 py-2">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we may improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
        </ul>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Retention of Data</h2>
        <p class="py-2">Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p class="py-2">Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Transfer Of Data</h2>
        <p class="py-2">Your information, including Personal Data, may be transferred to &mdash; and maintained on &mdash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
        <p class="py-2">If you are located outside the state of Ohio, USA, and choose to provide information to us, please note that we transfer the data, including Personal Data, to our servers and data stores in Ohio, USA, and process it there.</p>
        <p class="py-2">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p class="py-2">Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Disclosure Of Data</h2>
        <h3 class="font-bold md:text-lg mt-10">Business Transaction</h3>
        <p class="py-2">If Company is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <h3 class="font-bold md:text-lg mt-10">Disclosure for Law Enforcement</h3>
        <p class="py-2">Under certain circumstances, Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
        <h3 class="font-bold md:text-lg mt-10">Legal Requirements</h3>
        <p class="py-2">Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul class="list-disc ml-10 py-2">
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Company&nbsp;</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
        </ul>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Security Of Data</h2>
        <p class="py-2">The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">"Do Not Track" Signals</h2>
        <p class="py-2">We do not support Do Not Track ("DNT"). Do Not Track is a preference you may set in your web browser to inform websites that you do not want to be tracked.</p>
        <p class="py-2">You may enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Your Rights</h2>
        <p class="py-2">Company aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
        <p class="py-2">Whenever made possible, you may update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.</p>
        <p class="py-2">If you wish to be informed of what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
        <p class="py-2">In certain circumstances, you have the right:</p>
        <ul class="list-disc ml-10 py-2">
            <li>To access and receive a copy of the Personal Data we hold about you</li>
            <li>To rectify any Personal Data held about you that is inaccurate</li>
            <li>To request the deletion of Personal Data held about you</li>
        </ul>
        <p class="py-2">You have the right to data portability for the information you provide to Company. You may request to obtain a copy of your Personal Data in a commonly used electronic format so that you may manage and move it.</p>
        <p class="py-2">Please note that we may ask you to verify your identity before responding to such requests.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Service Providers</h2>
        <p class="py-2">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
        <p class="py-2">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        <h3 class="font-bold md:text-lg mt-10">Analytics</h3>
        <p class="py-2">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
        <p class="py-2">Google Marketing Platform</p>
        <p class="py-2">Google Marketing Platform is an advertising and analytics platform offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
        <p class="py-2">You may opt-out of having made your activity on the Service available to Google Marketing Platform by visiting the Google Marketing Platform opt-out page or the Network Advertising Initiative opt-out page. Additionally, you may opt-out by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
        <p class="py-2">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a class="text-blue-600" href="http://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy/</a></p>
        <h3 class="font-bold md:text-lg mt-10">Behavioral Remarketing</h3>
        <p class="py-2">Company uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>
        <p class="py-2">Google AdWords</p>
        <p class="py-2">Google AdWords remarketing service is provided by Google Inc.</p>
        <p class="py-2">You may opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a class="text-blue-600" href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a></p>
        <p class="py-2">Google also recommends installing the Google Analytics Opt-out Browser Add-on - <a class="text-blue-600" href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</p>
        <p class="py-2">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a class="text-blue-600" href="http://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy/</a></p>
        <p class="py-2">Facebook</p>
        <p class="py-2">Facebook remarketing service is provided by Facebook Inc.</p>
        <p class="py-2">You may learn more about interest-based advertising from Facebook by visiting this page: <a class="text-blue-600" href="https://www.facebook.com/help/164968693837950">https://www.facebook.com/help/164968693837950</a></p>
        <p class="py-2">To opt-out from Facebook's interest-based ads follow these instructions from Facebook: <a class="text-blue-600" href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a></p>
        <p class="py-2">Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You may also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a class="text-blue-600" href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a class="text-blue-600" href="http://youradchoices.ca/">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a class="text-blue-600" href="http://www.youronlinechoices.eu/">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.</p>
        <p class="py-2">For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a class="text-blue-600" href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p>
        <p class="py-2">Other Third-Party Services</p>
        <p class="py-2">We use additional third-party services to facilitate the Services on your behalf. For more information on the privacy practices of each of these Third-Party services, we have provided hyperlinks for your convenience. <br /><br /></p>
        <table class="table-auto">
            <tbody>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Service</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Service Provided</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Terms &amp; Privacy</p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Google</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Email, marketing&nbsp;</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="http://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy/</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Facebook</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Marketing</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Stripe</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Payment processor</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://stripe.com/en-ca/privacy">https://stripe.com/en-ca/privacy</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Paypal</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Payment processor</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://www.paypal.com/ca/webapps/mpp/ua/privacy-full?locale.x=en_CA">https://www.paypal.com/ca/webapps/mpp/ua/privacy-full?locale.x=en_CA</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Typeform</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Student surveys</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://admin.typeform.com/to/dwk6gt/">https://admin.typeform.com/to/dwk6gt/</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Unbounce</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Marketing landing pages</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://unbounce.com/privacy/">https://unbounce.com/privacy/</a></p>
                </td>
            </tr>
            <tr>
                <td class="border py-2 px-4">
                    <p class="py-2">Bonjoro</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2">Student relationship management</p>
                </td>
                <td class="border py-2 px-4">
                    <p class="py-2"><a class="text-blue-600" href="https://www.bonjoro.com/privacy-policy">https://www.bonjoro.com/privacy-policy</a></p>
                </td>
            </tr>
            </tbody>
        </table>
        <p class="py-2"></p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Links To Other Sites</h2>
        <p class="py-2">Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p class="py-2">We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Affiliate Disclosure</h2>
        <h3 class="font-bold md:text-lg mt-10">Amazon</h3>
        <p class="py-2">Musora Media is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to amazon (.com, .co.uk, .de, etc.) and any other website that may be affiliated with Amazon Service LLC Associates Program.</p>
        <p class="py-2">The affiliate links earn us a small commission on any purchase you make when you visit Amazon after clicking on an affiliate link. This adds no extra cost to your purchase.</p>
        <h3 class="font-bold md:text-lg mt-10">Other Affiliate Networks</h3>
        <p class="py-2">Aside from the Amazon Associates Program, Musora Media is a part of several other affiliate networks, including Impact, Thomann, and Commission Junction.</p>
        <p class="py-2">Being a part of these networks makes it possible to support a team of writers who help provide the latest and most in-depth information about the world of music. Opinions presented on the site are those of Musora Media, or our team of writers who at times may post their own opinions.</p>
        <p class="py-2">We greatly appreciate it when you choose to use our links to buy products and we aim to be upfront about products we receive compensation for -- and again, these add no extra costs to any of your purchases.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Children's Privacy</h2>
        <p class="py-2">Our Service does not address anyone under the age of 18 ("Children").</p>
        <p class="py-2">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Changes To This Privacy Policy</h2>
        <p class="py-2">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p class="py-2">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
        <p class="py-2">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        <h2 class="font-bold md:text-2xl mt-10 mb-4">Contact Us</h2>
        <p class="py-2">If you have any questions about this Privacy Policy, please <a class="text-blue-600" href="{{ get_musora_brand_base_url() }}/contact">contact us</a>.</p>
    </div>


    @include("drumeo.sales.partials._footer")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('/marketing/parcel/drumeo/navigation-sales.js') }}"></script>
@stop
