<?php

    $product = (object)[
        'bundles' => [
            [
                'name' => '5-Year Pianote Membership',
                'price' => 720,
                'bundle_desc' => 'Discover the best online piano lessons experience with Pianote. Your Pianote membership will give you hundreds of expertly designed, step-by-step lessons to guide you along the path to musical freedom. And you’ll get access to REAL teachers who will be able to answer any questions you have along the way.',
                'bundle_img' => 'https://pianote.s3.amazonaws.com/shop/products/5-for-3-bundle/pianote-5-year-card.jpg',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
            [
                'name' => '',
                'price' => 0,
                'bundle_desc' => '',
                'bundle_img' => '',
                'bundle_free_shipping' => true,
                'lifetime_access' => true,
                'free_bonus' => true,
            ],
        ]
    ];
