<?php

return [
    // brand
    'brand' => 'drumeo', // this is what will go in the brand column for requests to this project

    // database
    'database_connection_name' => env('DB_DEFAULT_CONNECTION_NAME', 'musora_laravel_mysql'),
    'data_mode' => 'host', // 'host' or 'client', hosts do the db migrations, clients do not
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_bin',

    // these are the urls/methods which should be captured by the middleware and processed by this package

    // the data map tells the middleware which input variables map to which attributes that are required
    // by the package
    'requests_to_capture' => [
        //--------------------------------------------------
        // drumeo
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Kristinas Top 25',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '40 Songs',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'COOP3RDRUMM3R - CC HTSPD - Lead Gen',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drum Set Maintenance',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Fastest Way To Get Faster',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Double Bass 101',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Jazz Drumming 101',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Better Doubles In 10 Days',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Drums',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Hand Technique',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Linear Drumming',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Grooves Of Michael Jackson',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Must-Know Drum Grooves',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Sucherman Sound',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Ultimate Drumming Toolbox',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Fastest Way To Get Faster - Facebook',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Drums - Facebook',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Drums - Thrive',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Gavins Grooves',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Free Play-Alongs',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Metal Play-Alongs',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Grooves Of John Bonham',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Blog Signup',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '2 Million Celebration',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drumeo Giveaway',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drumeo Drumset Giveaway',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drumeo Giveaway Rafflepress',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drumeo Awards Giveaway',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Drumeo Awards Giveaway 2',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '30 Day Drummer Waitlist',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '30 Day Chops Waitlist',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Alesis Waitlist',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'EarDrums Waitlist',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        //--------------------------------------------------
        // pianote
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Metronome Notice',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Chord Hacks - Facebook',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Chord Hacks',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Technique Essentials',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Blues Piano Bootcamp',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Piano - Facebook',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Piano',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Piano V3',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Learn 3 Songs On Piano',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Beginner Piano Christmas Carols',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Beautiful Christmas Classics',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Digital Chords And Scales',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'NPPSH Waitlist',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Easy Chords Waitlist',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '50 Chord Charts',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Sight Reading Made Simple',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Blog Signup',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Easy Classical Songs',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'F Sharp Minor',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Minor Blues Made Easy',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pentatonic Scale',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Practice Chord Inversions',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Riffs And Fills',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '1 Million',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Classical Piano Quick Start',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Piano In 5 Days',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Magic of Piano Chords Bootcamp',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Piano For Complete Beginners Bootcamp',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Perfect Practice Bootcamp',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Giveaway Form',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'FP30 Giveaway',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Casio Privia Giveaway',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Awards Giveaway',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Osmose Giveaway',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => '7 Days To Sight Reading',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Waltz in A Minor',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Personality Quiz Academic',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Personality Quiz Entertainer',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Personality Quiz Explorer',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Personality Quiz Scientist',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Webinar',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote webinar Joined',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Webinar Watched',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Webinar Replay Watched',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Webinar Missed',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Pianote Webinar Finished',
            'brand' => 'pianote',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        //--------------------------------------------------
        // guitareo
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Acoustic Guitar Jump Start',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Guitar Chords for Hit songs',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Beginner Guitar Starter',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Guitarists Toolbox',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Guitar Tricks',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'GQ Waitlist',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'leadtracker_form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Song Hour',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Fretboard Cheatsheet',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Solo In An Hour',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Acoustic Guitar',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Getting Started On The Electric Guitar',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Blog Signup',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Guitareo Waitlist 2',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Live Bootcamp',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Chord Bootcamp',
            'brand' => 'guitareo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        //--------------------------------------------------
        // singeo
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Improve Any Voice',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Holiday Karaoke',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Singeo Waitlist',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Singeo Waitlist 2',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Stop Hating Your Voice',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Studio Giveaway',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Eikon Giveaway',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Ultimate Giveaway',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Mic Giveaway',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Vocal Bootcamp',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Breath Bootcamp',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Harmony Bootcamp',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Blog Signup',
            'brand' => 'singeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        //--------------------------------------------------
        // musora
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Playlist - Musora Newsletter',
            'brand' => 'drumeo',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'The Playlist - Musora Newsletter',
            'brand' => 'musora',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
        [
            'path' => '/customer-io/submit-email-form-rc',
            'method' => 'post',
            'form_name' => 'Youtube Resources',
            'brand' => 'musora',

            'input_data_map' => [
                'email' => 'email',
                'form_name' => 'form_name',
                'utm_source' => 'leadtracker_utm_source',
                'utm_medium' => 'leadtracker_utm_medium',
                'utm_campaign' => 'leadtracker_utm_campaign',
                'utm_term' => 'leadtracker_utm_term',
                'customer_io_customer_id' => 'leadtracker_customer_io_customer_id',
                'customer_io_event_name' => 'leadtracker_customer_io_event_name',
            ],
        ],
    ],
];
