<?php

return [
    'auth-middleware' => ['api_authenticated', 'auth:sanctum',
        \Railroad\MusoraApi\Middleware\SetCustomDecorators::class
    ],
//        [
////        \Railroad\MusoraApi\Middleware\MobileAppTokenAuth::class,
//        \Railroad\MusoraApi\Middleware\SetCustomDecorators::class,
//        \Railroad\MusoraApi\Middleware\BrandMiddleware::class,
//        \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
//
////        \App\Http\Middleware\SetContentPermissions::class,
////        \Railroad\EventDataSynchronizer\Middleware\UserActivitySyncMiddleware::class
//    ],
    'user-middleware' => [
//        \Railroad\MusoraApi\Middleware\AuthIfTokenExist::class,
    ],
    'shouldDisplayReview' => true,
    'response-structure' => [
        'catalogues' => [
            'id',
            'brand',
            'popularity',
            'data.thumbnail_url',
            'type',
            'published_on',
            'status',
            'fields.title',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'instructors',
            'fields.artist',
            'fields.style',
            'fields.video.fields.length_in_seconds',
            'parent_id',
            'fields.name',
            'data.head_shot_picture_url',
            'isLive',
            'is_liked_by_current_user',
            'like_count',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'fields.live_event_start_time',
            'fields.live_event_end_time',
            '*fields.focus',
            '*fields.genre',
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'fields.is_active',
            'fields.is_featured',
            'is_house_coach',
            'data.focus_text',
            'data.banner_background_image_url',
            'data.forum_thread_url',
            'current_user_is_subscribed',
            'coach_card_image',
            'coach_bottom_banner_image',
            'coach_top_banner_image',
            'coach_profile_image',
            'coach_featured_image',
            'short_bio',
            'long_bio',
            'focus',
            'genre',
            'lesson_count',
            'lessons' => [
                'id',
            ],
        ],

        'instructor' => [
            'id',
            'fields.name',
            'data.biography',
            'data.head_shot_picture_url',
            'fields.is_active',
            'fields.is_featured',
            'is_house_coach',
            'forum_thread_id',
            'forum_thread',
            'lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'total_lessons',
            'lessons_filter_options',
            'lessons_filter_options_v2',
            'total_comments',
            'comments',
            'duration_in_seconds',
            'total_xp',
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'fields.video.fields.length_in_seconds',
            'current_user_is_subscribed',
            'featured_lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'coach_card_image',
            'coach_bottom_banner_image',
            'coach_top_banner_image',
            'coach_profile_image',
            'coach_featured_image',
            'short_bio',
            'long_bio',
            'focus',
            'genre',
            'bands',
            'endorsements'
        ],

        'instructor-filter' => [
            'id',
            'fields.name',
            'data.head_shot_picture_url',
            'type',
        ],

        'coach' => [
            'id',
            'fields.name',
            'fields.is_active',
            'fields.is_featured',
            'is_house_coach',
            'biography',
            'data.head_shot_picture_url',
            'lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'total_lessons',
            'lessons_filter_options',
            'lessons_filter_options_v2',
            'total_comments',
            'comments',
            'duration_in_seconds',
            'total_xp',
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'fields.video.fields.length_in_seconds',
            'current_user_is_subscribed',
            'featured_lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'coach_card_image',
            'coach_bottom_banner_image',
            'coach_top_banner_image',
            'coach_profile_image',
            'coach_featured_image',
            'short_bio',
            'long_bio',
            'focus',
            'genre',
            'bands',
            'endorsements'
        ],

        'coach-filter' => [
            'id',
            'fields.name',
            'data.head_shot_picture_url',
            'type',
        ],

        'pack-bundle' => [
            'id',
            'type',
            'fields.title',
            'data.description',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'is_owned',
            'full_price',
            'price',
            'pack_logo',
            'apple_product_id',
            'google_product_id',
            'lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'current_lesson_index',
            'mobile_app_url',
            'next_lesson' => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'current_lesson' => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'next_bundle' => [
                'id',
                'type',
                'mobile_app_url',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'pack-bundle-lesson' => [
            'id',
            'type',
            'fields.title',
            'is_owned',
            'data.description',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'resources',
            'related_lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'next_lesson' => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
            ],
            'parent',
            'bundle_count',
            'next_content_type',
            'total_comments',
            'comments',
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'fields.video.fields.length_in_seconds',
            'xp',
            'total_xp',
            'xp_bonus',
            'published_on',
            'is_added_to_primary_playlist',
            'is_liked_by_current_user',
            'like_count',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
        ],

        'course' => [
            'id',
            'data.thumbnail_url',
            'type',
            'published_on',
            'status',
            'fields.title',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'is_added_to_primary_playlist',
            'instructors',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
            'length_in_seconds',
            'data.description',
            'xp',
            'xp_bonus',
            'duration',
            'is_liked_by_current_user',
            'like_count',
            'current_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            '*fields.instructor',
            'total_length_in_seconds',
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
        ],

        'course-part' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'total_comments',
            'comments',
            'xp',
            'xp_bonus',
            'instructor' => [
                'id',
                'fields.name',
                'data.biography',
                'data.head_shot_picture_url',
            ],
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'data.description',
            'data.captions',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent' => [
                'id',
                'fields.title',
                'xp',
                'current_lesson' => [
                    'id',
                    'mobile_app_url',
                    'musora_api_mobile_app_url',
                ]
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'play-along' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'comments',
            'total_comments',
            'xp',
            'xp_bonus',
            '*fields.instructor',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'data.description',
            'data.captions',
            'data.mp3_no_drums_no_click_url',
            'data.mp3_no_drums_yes_click_url',
            'data.mp3_yes_drums_no_click_url',
            'data.mp3_yes_drums_yes_click_url',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent',
            'fields.artist',
            'fields.style',
        ],

        'song' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'comments',
            'total_comments',
            'xp',
            'xp_bonus',
            '*fields.instructor',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'data.description',
            'data.captions',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent',
            'fields.artist',
            'fields.style',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'coach-stream' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'comments',
            'total_comments',
            'xp',
            'xp_bonus',
            '*fields.instructor',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'data.description',
            'data.captions',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent',
            'fields.artist',
            'fields.style',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'top-header-pack' => [
            'id',
            'type',
            'started',
            'completed',
            'is_new',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'next_lesson_url',
            'bundle_count',
            'thumbnail',
            'pack_logo',
            'full_price',
            'price',
            'is_owned',
        ],

        'my-packs' => [
            'id',
            'type',
            'is_new',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'bundle_count',
            'thumbnail',
            'pack_logo',
        ],

        'more-packs' => [
            'id',
            'type',
            'is_new',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'bundle_count',
            'thumbnail',
            'pack_logo',
            'is_locked',
            'price',
        ],

        'live-schedule' => [
            'id',
            'type',
            'fields.title',
            'fields.live_event_start_time',
            'fields.live_event_end_time',
            'data.thumbnail_url',
            'published_on',
            'is_added_to_primary_playlist',
            'fields.length_in_seconds',
            'parent_id',
            'completed',
            'started',
            'instructors',
            'isLive',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'live' => [
            'id',
            'popularity',
            'type',
            'isLive',
            'fields.title',
            'fields.live_event_start_time',
            'fields.live_event_end_time',
            'is_added_to_primary_playlist',
            'data.thumbnail_url',
            'instructors',
            'instructor_head_shot_picture_url',
            'chatRollEmbedUrl',
            'chatRollViewersNumberClass',
            'youtube_video_id',
            'chatRollStyle',
            'apiKey',
            'chatChannelName',
            'questionsChannelName',
            'token',
            'userId',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'pack' => [
            'id',
            'type',
            'fields.title',
            'data.description',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'is_owned',
            'thumbnail',
            'pack_logo',
            'apple_product_id',
            'google_product_id',
            'child_ids',
            'bundles' => [
                'fields.title',
                'data.thumbnail_url',
                'id',
                'progress_percent',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'lesson_count',
                'like_count',
            ],
            "current_lesson_index",
            "bundle_number",
            "next_lesson" => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'parent_id',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'semester-pack' => [
            'id',
            'type',
            'fields.title',
            'data.description',
            'url',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'is_owned',
            'thumbnail',
            'pack_logo',
            'apple_product_id',
            'google_product_id',
            'lessons' => [
                'fields.title',
                'type',
                'data.thumbnail_url',
                'id',
                'progress_percent',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'lesson_count',
                'like_count',
                'fields.video.fields.length_in_seconds',
                'is_added_to_primary_playlist',
                'published_on',
                'completed',
                'started'
            ],
            "current_lesson_index",
            "next_lesson" => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'parent_id',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'semester-pack-lesson' => [
            'id',
            'type',
            'fields.title',
            'is_owned',
            'data.description',
            'completed',
            'started',
            'progress_percent',
            'user_progress',
            'resources',
            'related_lessons' => [
                'id',
                'type',
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'next_lesson' => [
                'fields.title',
                'fields.artist',
                'fields.style',
                'data.thumbnail_url',
                'id',
                'type',
                'status',
                'published_on',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'fields.video.fields.length_in_seconds',
                'is_liked_by_current_user',
                'parent_id',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
            ],
            'parent',
            'next_content_type',
            'total_comments',
            'comments',
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'fields.video.fields.length_in_seconds',
            'xp',
            'total_xp',
            'xp_bonus',
            'published_on',
            'is_added_to_primary_playlist',
            'is_liked_by_current_user',
            'like_count',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'assignment' => [
            'id',
            'xp',
            'user_progress',
            'fields.title',
            'fields.soundslice_slug',
            'data.description',
            '*data.sheet_music_image_url',
            'data.timecode',
        ],

        'comment' => [
            'is_liked',
            'like_count',
            'user_id',
            'id',
            'replies',
            'user' => [
                'fields.profile_picture_image_url',
                'xp',
                'display_name',
                'xp_level',
            ],
            'comment',
            'created_on',
        ],

        'learning-path' => [
            'id',
            'started',
            'completed',
            'level_rank',
            'fields.title',
            'fields.video.fields.vimeo_video_id',
            'data.description',
            'data.thumbnail_url',
            'published_on',
            'levels' => [
                'id',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'published_on',
                'data.description',
                'data.thumbnail_url',
                'position',
                'progress_percent',
                'fields.title',
                '*fields.instructor',
            ],
            'lesson_rank',
            'progress_percent',
            'video_playback_endpoints',
            'banner_button_url',
            'banner_background_image',
            'fields.video.fields.length_in_seconds',
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'status',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'learning-path-level' => [
            'id',
            'type',
            'fields.title',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            '*fields.instructor',
            'data.description',
            'data.thumbnail_url',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'level_number',
            'banner_background_image',
            'total_xp',
            'started',
            'completed',
            'progress_percent',
            'video_playback_endpoints',
            'length_in_seconds',
            'banner_button_url',
            'is_added_to_primary_playlist',
            'published_on',
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'status',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'courses' => [
                'id',
                'fields.title',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'level_rank',
                'data.thumbnail_url',
                'is_added_to_primary_playlist',
                'progress_percent',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'learning-path-course' => [
            'id',
            'type',
            'is_added_to_primary_playlist',
            'started',
            'completed',
            'fields.title',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'data.thumbnail_url',
            'data.description',
            'progress_percent',
            'xp',
            'total_xp',
            'duration',
            'banner_button_url',
            'published_on',
            'is_liked_by_current_user',
            'like_count',
            'total_length_in_seconds',
            'level_position',
            'course_position',
            '*fields.instructor',
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'status',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'lessons' => [
                'id',
                'type',
                'published_on',
                'started',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'learning-path-lesson' => [
            'id',
            'type',
            'fields.title',
            'mobile_app_url',
            'musora_api_mobile_app_url',
            'fields.video.fields.length_in_seconds',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'instructor' => [
                'id',
                'fields.name',
                'data.biography',
                'data.head_shot_picture_url',
            ],
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
            'data.description',
            'data.thumbnail_url',
            'chapters',
            'total_xp',
            'xp',
            'user_progress',
            'published_on',
            'next_lesson_id',
            'next_lesson_thumbnail_url',
            'next_lesson_title',
            'next_lesson_url',
            'nextLessonLengthInMinValue',
            'is_last_incomplete_lesson_from_course',
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'status',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'status',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'current_course' => [
                'id',
                'fields.title',
                'fields.xp',
                'data.thumbnail_url',
            ],
            'next_course' => [
                'id',
                'fields.title',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'level_rank',
                'data.thumbnail_url',
                'lesson_count',
            ],
            'current_level' => [
                'id',
                'fields.title',
                'fields.xp',
                'level_number',
                'data.thumbnail_url',
            ],
            'next_level' => [
                'id',
                'fields.title',
                'mobile_app_url',
                'musora_api_mobile_app_url',
                'level_number',
                'data.thumbnail_url',
                'published_on',
                'is_added_to_primary_playlist',
            ],
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'is_liked_by_current_user',
            'like_count',
            'is_added_to_primary_playlist',
            'level_position',
            'course_position',
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'started',
                'completed',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'fields.video.fields.length_in_seconds',
                'data.thumbnail_url',
                'mobile_app_url',
                'musora_api_mobile_app_url',
            ],
            'comments',
            'total_comments',
            'video_playback_endpoints',
            'captions',
            'last_watch_position_in_seconds',
            'last_incomplete_lesson_from_course',
            'is_last_incomplete_course_from_level',
            'resources',
        ],

        'student-focus' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'total_comments',
            'comments',
            'xp',
            'xp_bonus',
            '*fields.instructor',
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'data.description',
            'data.captions',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent',
            'fields.live_event_start_time',
            'fields.live_event_end_time',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'show-lesson' => [
            'id',
            'type',
            'published_on',
            'completed',
            'started',
            'progress_percent',
            'is_added_to_primary_playlist',
            'fields.title',
            'length_in_seconds',
            'data.thumbnail_url',
            'total_comments',
            'comments',
            'xp',
            'xp_bonus',
            'instructor' => [
                'id',
                'fields.name',
                'data.biography',
                'data.head_shot_picture_url',
            ],
            'fields.video.fields.vimeo_video_id',
            'fields.video.fields.youtube_video_id',
            'fields.video.fields.length_in_seconds',
            'data.description',
            'data.captions',
            'like_count',
            'is_liked_by_current_user',
            'chapters',
            'user_progress',
            'resources',
            'assignments' => [
                'id',
                'xp',
                'user_progress',
                'fields.title',
                'fields.soundslice_slug',
                'data.description',
                '*data.sheet_music_image_url',
                'data.timecode',
            ],
            'related_lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'next_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'previous_lesson' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
            ],
            'video_playback_endpoints',
            'last_watch_position_in_seconds',
            'parent',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'download' => [
            'lessons' => [
                'id',
                'type',
                'published_on',
                'completed',
                'started',
                'progress_percent',
                'is_added_to_primary_playlist',
                'fields.title',
                'length_in_seconds',
                'data.thumbnail_url',
                'video_playback_endpoints',
                'last_watch_position_in_seconds',
                'fields.video.fields.vimeo_video_id',
                'fields.video.fields.youtube_video_id',
                'fields.video.fields.length_in_seconds',
                'resources',
                'assignments' => [
                    'id',
                    'xp',
                    'user_progress',
                    'fields.title',
                    'fields.soundslice_slug',
                    'data.description',
                    '*data.sheet_music_image_url',
                    'data.timecode',
                ],
                'comments',
                'total_comments',
                'related_lessons' => [
                    'id',
                    'type',
                    'fields.title',
                    'fields.artist',
                    'fields.style',
                    'data.thumbnail_url',
                    'status',
                    'published_on',
                    'completed',
                    'progress_percent',
                    'is_added_to_primary_playlist',
                    'mobile_app_url',
                    'musora_api_mobile_app_url',
                    'length_in_seconds',
                    'is_liked_by_current_user',
                    'parent_id',
                ],
                'next_lesson' => [
                    'fields.title',
                    'fields.artist',
                    'fields.style',
                    'data.thumbnail_url',
                    'id',
                    'type',
                    'status',
                    'published_on',
                    'completed',
                    'progress_percent',
                    'is_added_to_primary_playlist',
                    'mobile_app_url',
                    'musora_api_mobile_app_url',
                    'length_in_seconds',
                    'is_liked_by_current_user',
                    'parent_id',
                ],
                'previous_lesson' => [
                    'id',
                    'type',
                    'published_on',
                    'completed',
                    'started',
                    'progress_percent',
                    'is_added_to_primary_playlist',
                    'fields.title',
                    'length_in_seconds',
                    'data.thumbnail_url',
                ],
                'user_progress',
                'course_position',
                'level_position',
                'total_xp',
                'xp'
            ],
            '*fields.instructor',
            'coaches' => [
                'id',
                'fields.name',
                'coach_profile_image',
                'current_user_is_subscribed',
            ],
        ],

        'profile' => [
            'id',
            'email',
            'display_name',
            'avatarUrl',
            'totalXp',
            'xpRank',
            'isEdge',
            'isEdgeExpired',
            'edgeExpirationDate',
            'isPackOlyOwner',
            'isAppleAppSubscriber',
            'isGoogleAppSubscriber',
            'notify_weekly_update',
            'notify_on_lesson_comment_reply',
            'notify_on_lesson_comment_like',
            'notify_on_forum_followed_thread_reply',
            'notify_on_forum_post_like',
            'notify_on_forum_post_reply',
            'notifications_summary_frequency_minutes',
            'permission_level',
            'helpscout_beacon_id'
        ],
    ],
    'brand_logo_path_for_email' => [
        'drumeo' => 'https://dmmior4id2ysr.cloudfront.net/logos/drumeo-logo.png',
        'pianote' => "https://dmmior4id2ysr.cloudfront.net/logos/pianote-logo-red.png",
    ],
    'submit_question_subject' => [
        'drumeo' => "Weekly Q&A submission from: ",
        'pianote' => "Question Asked by: ",
    ],
    'submit_question_recipient' => [
        'drumeo' => 'support+question-and-answer@drumeo.com',
        'pianote' => 'team+question-and-answer@pianote.com',
    ],
    'submit_question_success_message' => [
        'drumeo' => "Your question has been submitted successfully and will be scheduled into one of our weekly Question and Answer sections! You will receive an email so you can check it out live, or here in the archives when you have time.",
        'pianote' => "Question successfully sent!",
    ],
    'submit_video_recipient' => [],
    'submit_student_focus_recipient' => [
        'pianote' => 'team+studentreviews@pianote.com',
        'drumeo' => 'support+student-focus@drumeo.com'
    ],
    'submit_student_focus_success_message' => [
        'drumeo' => 'Your submission has been sent to a Drumeo Instructor. Typically, they\'ll email you within 48 hours to let you know when your review and custom Student Plan will be ready!',
        'pianote' => 'You\'ll be hearing from us soon!',
    ],
];
