<?php

// IMPORTANT NOTICE: this is only for the legacy rail permissions package.
return [
    'cache_duration' => 60 * 60 * 24 * 30,
    'cache_driver' => 'array',

    'database_connection_name' => 'musora_laravel_mysql',
    'database_mode' => 'host',

    'table_prefix' => 'permissions_',
    'tables' => [
        'user_abilities' => 'user_abilities',
        'user_roles' => 'user_roles',
    ],

    'role_abilities' => [
        'administrator' => [
            'like-posts',
            'index-posts',
            'show-posts',
            'create-posts',
            'update-posts' => ['only' => ['content', 'thread_id', 'created_at']],
            'delete-posts',
            'read-threads',
            'follow-threads',
            'create-threads',
            'update-threads' => ['only' => ['title', 'category_id', 'created_at', 'locked', 'pinned']],
            'delete-threads',
            'report-posts',
            'index-users',
            'chat.ban_user',
            'chat.unban_user',
            'chat.delete_user_messages',
            'index-threads',
            'index-discussions',
            'show-discussions',
            'create-discussions',
            'update-discussions' => ['only' => ['title', 'topic', 'description','icon']],
            'delete-discussions',
        ],
        'moderator' => [
            'like-posts',
            'index-posts',
            'show-posts',
            'create-posts',
            'update-posts' => ['only' => ['content', 'thread_id']],
            'delete-posts',
            'read-threads',
            'follow-threads',
            'create-threads',
            'update-threads' => ['only' => ['title', 'category_id', 'created_at', 'locked', 'pinned']],
            'delete-threads',
            'report-posts',
            'chat.ban_user',
            'chat.unban_user',
            'chat.delete_user_messages',
            'index-threads',
            'index-discussions',
            'show-discussions',
            'create-discussions',
            'update-discussions' => ['only' => ['title', 'topic', 'description','icon']],
            'delete-discussions',
        ],
        'user' => [
            'like-posts',
            'index-posts',
            'show-posts',
            'create-posts',
            'read-threads',
            'follow-threads',
            'create-threads',
            'report-posts',
            'index-threads',
            'index-discussions',
            'show-discussions',
            'create-discussions'
        ],
    ],
];
