<?php

return [
    'fields' => [
        'title',
        'difficulty',
        'album',
        'xp',
        'fast_bpm',
        'slow_bpm',
        'home_staff_pick_rating',
        'legacy_id',
        'legacy_wordpress_post_id',
        'qna_video',
        'style',
        'artist',
        'bpm',
        'cd_tracks',
        'chord_or_scale',
        'difficulty_range',
        'episode_number',
        'exercise_book_pages',
        'instructors',
        'live_event_start_time',
        'live_event_end_time',
        'live_event_youtube_id',
        'live_stream_feed_type',
        'name',
        'released',
        'total_xp',
        'transcriber_name',
        'week',
        'avatar_url',
        'soundslice_slug',
        'staff_pick_rating',
        'student_id',
        'vimeo_video_id',
        'youtube_video_id',
        'length_in_seconds',
        'video',
        'topic',
        'tag',
        'key',
        'key_pitch_type',
        'playlist',
        'instructor',
    ],
    'request_attributes' => [
        'comment',
        'display_name',
        'status',
        'slug',
        'type',
        'brand',
        'sort',
        'language',
        'key',
        'value',
        'position',
        'fields',
        'content_type',
        'name',
        'start_date',
        'expiration_date',
        'progress_percent',
        'published_on',
        'created_on',
        'archived_on',
    ],
    'request_relationships' => [
        'content_id' => 'content',
        'permission_id' => 'permission',
        'user_id' => 'user',
    ],
];