<?php

$product = (object)[
    'bundles' => [
        [
            'name' => '5-Year Drumeo Membership',
            'price' => 1200,
            'special_text' => 'SAVE 40%',
            'bundle_desc' => 'Get better, faster with Drumeo’s award-winning online drum lessons taught by the world’s greatest drummers. You’ll always know what to practice with step-by-step lessons, 5000+ note-for-note song breakdowns, hundreds of drum-less playalongs, and ongoing support & motivation from pro drummers. ',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/drum-shop/5-for-3-bundle/drumeo-5-year-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => false,
            'free_bonus' => false,
        ],
        [
            'name' => 'Drumeo EarDrums',
            'price' => 197,
            'special_text' => '',
            'bundle_desc' => 'Drumeo EarDrums reduce external volume by up to -29dB. That means you can play hard while protecting your ears.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/ear-drums-card.jpg',
            'bundle_free_shipping' => true,
            'lifetime_access' => false,
            'free_bonus' => true,
        ],
        [
            'name' => 'Drumeo Drumsticks',
            'price' => 12.95,
            'special_text' => '',
            'bundle_desc' => 'The Drumeo 5A Drumsticks by Vater -- made of hickory for strength and durability, featuring up to 2X the moisture content than most manufacturers for longer-lasting sticks, and personally hand-rolled by Alan Vater to ensure they’re weighted and tone-matched to perfection.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/drumsticks.jpg',
            'bundle_free_shipping' => true,
            'lifetime_access' => false,
            'free_bonus' => true,
        ],
        [
            'name' => 'Electrify Your Drumming',
            'price' => 197,
            'bundle_desc' => 'Electrify Your Drumming will teach you the tools and styles of electronic dance music -- so you can build energy with risers, lock in with the vocals, add power to your beats and fills, create a climax in the music, and ultimately fuel any song with your playing -- giving you valuable skills that will apply to every style of music.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/eyd.jpg',
            'bundle_free_shipping' => true,
            'lifetime_access' => false,
            'free_bonus' => true,
        ],
        [
            'name' => 'Successful Drumming',
            'price' => 97,
            'special_text' => '',
            'bundle_desc' => 'The ultimate crash course to playing more creative and more musical drum fills your audience will love. Rather than memorizing and playing the same fills over and over again, you’ll gain the skills you need to create effective drum fills on the fly and adapt them to any musical setting.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/sd.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Rock Drumming Masterclass',
            'price' => 197,
            'special_text' => '',
            'bundle_desc' => 'Rock icon Todd Sucherman is your personal drum coach with a 26-week online course to rapidly improve your rock drumming. You’ll get weekly video lessons and exercises to improve your beats, fills, creativity, solos, bass drum combinations, hand technique, shuffles & variations, musicality, and more. ',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/rdm.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Drum Technique Made Easy',
            'price' => 197,
            'special_text' => '',
            'bundle_desc' => 'Technique guru Bruce Becker delivers an intimate 26-week course where you’ll get his proven process for improving your hand technique and foot technique so you can develop more speed and control around the kit -- all while preventing injuries & enjoying the music. ',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/dtme.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Independence Made Easy',
            'price' => 197,
            'special_text' => '',
            'bundle_desc' => 'Freedom starts here. Jared Falk’s 26-week course was built to unlock all four limbs so you can play more musical grooves, better sounding fills, and finally achieve the musical freedom that allows you to play whatever you want, whenever you want.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/ime.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Learn Songs Faster',
            'price' => 19,
            'special_text' => '',
            'bundle_desc' => 'A 75-minute masterclass with Jared Falk & Dave Atkinson to help you learn MORE songs in less time -- from active listening that’ll help you hear phrasing and understand song structure, to building effective grooves and fills, and keeping time so your playing always matches the music.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/lsf.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Anatomy of a Drum Solo | Neil Peart',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Drumming’s all-time greatest legend shows you his thoughtful approach to music’s most celebrated breakdown: the drum solo. Join Neil Peart as he explores the history of the drum solo and how you can build your own epic composition.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/anatomy-of-a-drum-solo-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Methods & Mechanics | Todd Sucherman',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Learn to strike with power & grace with expert guidance from award-winning Styx drummer, Todd Sucherman. Todd brings the knowledge of thousands of gigs, shows and recording sessions along with over three decades as a professional drummer to this useful and unique package.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/method-mechanics-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'The Language Of Drumming | Benny Greb',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'The Language of Drumming helps you express yourself through the drums by focusing on the most basic components. Benny Greb introduces his revolutionary 24-character system and shows you how to use the basic rhythms to develop timing, technique, dynamic control, and speed.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/the-language-of-drumming-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Great Hands For A Lifetime | Tommy Igoe',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Your pathway to playing better, faster, and healthier for a lifetime of pain-free drumming -- Great Hands For A Lifetime will help you unlock your potential and protect your hands for the many years of drumming to come.',
            'bundle_img' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/july/tommy_card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Hands Grooves & Fills | Pat Petrillo',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Hands, Grooves, & Fills is your complete curriculum for developing technique, groove ideas, and a drum fill vocabulary. Join veteran NYC drummer, Pat Petrillo, as he breaks down exercises to expand these three key areas of your drumming.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/hand-grooves-fills-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'In Constant Motion | Mike Portnoy',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'In Constant Motion features over seven hours of instruction, live and studio performances, and insights into Mike Portnoy’s numerous projects. Packed with audio and video, special features, and printable transcriptions of selected performances, the depth and diversity of this package is recommended for drummers of all interests and skill levels.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/in-constant-motion-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Creative Control | Thomas Lang',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Thomas Lang gives you an innovative & inspired practice regime that helps you develop incredible drumset technique. This course will forever change your relationship with four-way coordination, musical ostinatos, and more.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/creative-control-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'The Grid | Mike Mangini',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'With The Grid, Mike Mangini presents a complete system for expanding your skills as a creative player and improviser, focusing in on your own musical identity. You will increase your speed, develop better independence, learn how to use ostinatos, and become a more creative player.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/the-grid-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
        [
            'name' => 'Beyond The Chops | Aaron Spears',
            'price' => 29.99,
            'special_text' => '',
            'bundle_desc' => 'Be inspired with amazing performances, enlightening educational segments, and revealing interviews as Spears displays his natural talent, incredible groove, and deep skills in a set of performances with Gospel, R&B, Motown, rock, shuffle, and odd-meter tracks.',
            'bundle_img' => 'https://d1fyshwdvi6fth.cloudfront.net/Drumeo/Bundle-images/beyond-the-chops-card.jpg',
            'bundle_free_shipping' => false,
            'lifetime_access' => true,
            'free_bonus' => true,
        ],
    ]
];

$bonuses = [
    [
        'name' => 'Drumeo EarDrums',
        'price' => 149,
        'description' => 'Drumeo EarDrums reduce external volume by up to -29dB. That means you can play hard while protecting your ears.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/eardrums.jpg',
        'shipping' => true,
    ],
    [
        'name' => 'Drumeo Drumsticks',
        'price' => 12.95,
        'description' => 'Drumeo 5A Drumsticks by Vater -- made with hickory and extra moisture to last longer',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/drumsticks.jpg',
        'shipping' => true,
    ],
    [
        'name' => 'Hudson lessons',
        'price' => 270,
        'description' => 'These 9 lesson packs changed the game in drum education. Improve your independence, solos, and more!',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/drum-shop/5-for-3-bundle/hudson-pack-card.jpg',
    ],
    [
        'name' => 'Successful Drumming',
        'price' => 247,
        'description' => 'Jared Falk’s step-by-step curriculum for building a rock-solid foundation on the drum.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/sd.jpg',
    ],
    [
        'name' => 'Rock Drumming Masterclass',
        'price' => 197,
        'description' => 'Todd Sucherman’s 26-week masterclass to help you improve your rock drumming.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/rdm.jpg',
    ],
    [
        'name' => 'Drum Technique Made Easy',
        'price' => 197,
        'description' => 'Bruce Becker’s 26-week masterclass to improve your hand & foot technique.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/dtme.jpg',
    ],
    [
        'name' => 'Independence Made Easy',
        'price' => 197,
        'description' => 'Jared Falk’s 26-week masterclass to unlock your musicality and freedom on the drums.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/ime.jpg',
    ],
    [
        'name' => 'Learn Songs Faster',
        'price' => 19,
        'description' => 'Your guide to learning MORE songs in less time with Jared Falk & Dave Atkinson.',
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/lsf.jpg',
    ],
    [
        'image' => 'https://dpwjbsxqtam5n.cloudfront.net/promos/black-friday/bundles/vertical-bg/eyd.jpg',
        'title' => 'Electrify Your Drumming',
        'description' => 'Your guide to playing 10 styles of electronic dance music - includes 23 play-alongs!',
        'price' => 197,
    ],
];
