<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Modules\Content\Models\Content
 *
 * @property integer $id
 * @property integer $brand_id
 * @property string $title
 * @property string $subtitle
 * @property string $description
 * @property string $cta_text
 * @property string $cta_url
 * @property string $img
 * @property integer $display_order
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $start_date
 * @property Carbon $end_date
 * @property integer $visible
 * @property integer $is_featured
 * @property integer $product_id
 * @property string $product_url
 * @property string $endpoint
 * @property string $video_src
 */
class Carousel extends Model
{
    use HasFactory;

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    protected $guarded = [
        'id'
    ];

    protected $casts = [
        'start_date' => 'datetime',
        'end_date' => 'datetime',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model) {
            $uuid = $model['uuid'];
            unset($model['uuid']);

            if (gettype($model['img']) === 'object') {
                $model['img'] = 'https://laravel-nova.s3.us-east-2.amazonaws.com/' . $model->brand->name . '/carousels/' . $uuid . '-' . $model['img']->getClientOriginalName();
            }

            if (gettype($model['logo']) === 'object') {
                $model['logo'] = 'https://laravel-nova.s3.us-east-2.amazonaws.com/' . $model->brand->name . '/carousels/' . $uuid . '-' . $model['logo']->getClientOriginalName();
            }
        });
    }
}
