<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Carousel extends Model
{
    use HasFactory;

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    protected $guarded = [
        'id'
    ];

    protected $casts = [
        'start_date' => 'datetime',
        'end_date' => 'datetime',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model){
            $uuid = $model['uuid'];
            unset($model['uuid']);

            if(gettype($model['img']) === 'object'){
                $model['img'] = 'https://laravel-nova.s3.us-east-2.amazonaws.com/'.$model->brand->name.'/carousels/'.$uuid.'-'.$model['img']->getClientOriginalName();
            }
        });

    }
}
