<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
use Venturecraft\Revisionable\RevisionableTrait;


/**
 * App\Models\Cohort
 *
 * @property int $id
 * @property int $brand_id
 */
class Cohort extends Model
{
    use HasFactory;
//    use RevisionableTrait;

//
//    protected $with = ["brand", "productType"];

//    protected $revisionForceDeleteEnabled = true;
    protected $casts = [
        'enrollment_start_date' => 'datetime',
        'enrollment_end_date' => 'datetime',
        'cohort_start_date' => 'datetime',
        'cohort_end_date' => 'datetime',
    ];
    /**
     * Prepare a date for array / JSON serialization.
     */
    protected function serializeDate(\DateTimeInterface $date): string
    {
        return $date->format('Y-m-d H:d:i');
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    public function dropdowns()
    {
        return $this->hasMany(CohortDropdown::class);
    }

//    protected function slug(): Attribute
//    {
//        return Attribute::make(
//            get: fn ($value) => str_replace( array('Drumeo-', 'Pianote-', 'Guitareo-', 'Singeo-', 'Musora-'), '', $value ),
//        );
//    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model){
            $uuid = $model['uuid'];
            unset($model['uuid']);

//            if(!empty($model['slug'])){
//                $model['slug'] = $model->brand->name.'-'.$model['slug'];
//            }

            if(gettype($model['dark_mode_logo']) === 'object'){
                $model['dark_mode_logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/cohorts/'.$uuid.'-'.$model['dark_mode_logo']->getClientOriginalName();
            }

            if(gettype($model['light_mode_logo']) === 'object'){
                $model['light_mode_logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/cohorts/'.$uuid.'-'.$model['light_mode_logo']->getClientOriginalName();
            }

            if(gettype($model['header_image_url']) === 'object'){
                $model['header_image_url'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/cohorts/'.$uuid.'-'.$model['header_image_url']->getClientOriginalName();
            }

            if(gettype($model['body_image_url']) === 'object'){
                $model['body_image_url'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/cohorts/'.$uuid.'-'.$model['body_image_url']->getClientOriginalName();
            }

            if(gettype($model['body_logo']) === 'object'){
                $model['body_logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/cohorts/'.$uuid.'-'.$model['body_logo']->getClientOriginalName();
            }
        });

    }

    protected $guarded = [
        'id'
    ];
}
