<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
use Venturecraft\Revisionable\RevisionableTrait;


/**
 * App\Models\Cohort
 *
 * @property int $id
 * @property int $brand_id
 */
class Cohort extends Model
{
    use HasFactory;
//    use RevisionableTrait;

//
//    protected $with = ["brand", "productType"];

//    protected $revisionForceDeleteEnabled = true;
    protected $casts = [
        'start_date' => 'datetime',
        'end_date' => 'datetime',
    ];


    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    public function dropdowns()
    {
        return $this->hasMany(CohortDropdown::class);
    }

//    protected function slug(): Attribute
//    {
//        return Attribute::make(
//            get: fn ($value) => str_replace( array('Drumeo-', 'Pianote-', 'Guitareo-', 'Singeo-', 'Musora-'), '', $value ),
//        );
//    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model){

//            if(!empty($model['slug'])){
//                $model['slug'] = $model->brand->name.'-'.$model['slug'];
//            }

//            if(gettype($model['meta_img']) === 'object'){
//                $model['meta_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Meta-images/'.$uuid.'-'.$model['meta_img']->getClientOriginalName();
//            }
//
//            if(gettype($model['spread_img']) === 'object'){
//                $model['spread_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Spread-images/'.$uuid.'-'.$model['spread_img']->getClientOriginalName();
//            }
//
//            if(gettype($model['thumbnail']) === 'object'){
//                $model['thumbnail'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Thumbnails/'.$uuid.'-'.$model['thumbnail']->getClientOriginalName();
//            }
//
//            if(gettype($model['thumbnail_logo']) === 'object'){
//                $model['thumbnail_logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Thumbnail-logos/'.$uuid.'-'.$model['thumbnail_logo']->getClientOriginalName();
//            }
//
//            if(gettype($model['page_logo']) === 'object'){
//                $model['page_logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Page-logos/'.$uuid.'-'.$model['page_logo']->getClientOriginalName();
//            }
//
//            if(gettype($model['product_img']) === 'object'){
//                $model['product_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Product-images/'.$uuid.'-'.$model['product_img']->getClientOriginalName();
//            }
//
//            if(gettype($model['bundle_img']) === 'object'){
//                $model['bundle_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Bundle-images/'.$uuid.'-'.$model['bundle_img']->getClientOriginalName();
//            }
        });

    }

    protected $guarded = [
        'id'
    ];
}
