<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leadgen extends Model
{
    use HasFactory;

    protected $guarded = [
        'id'
    ];

    protected function casts(): array
    {
        return [
            'start_date' => 'datetime',
            'end_date' => 'datetime',
        ];
    }

    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    public function lessons(): HasMany
    {
        return $this->hasMany(LeadgenLesson::class)->orderBy('display_order');
    }

    public function assets(): HasMany
    {
        return $this->hasMany(LeadgenLessonAsset::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model) {
            $uuid = $model['uuid'];
            unset($model['uuid']);


            if(gettype($model['meta_img']) === 'object') {
                $model['meta_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Lead-gens/Meta-images/'.$uuid.'-'.str_replace(' ', '+', $model['meta_img']->getClientOriginalName());
            }

            if(gettype($model['logo']) === 'object') {
                $model['logo'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Lead-gens/Logos/'.$uuid.'-'.str_replace(' ', '+', $model['logo']->getClientOriginalName());
            }

            if(gettype($model['bg_img']) === 'object') {
                $model['bg_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/'.$model->brand->name.'/Lead-gens/Background-images/'.$uuid.'-'.str_replace(' ', '+', $model['bg_img']->getClientOriginalName());
            }
        });

    }
}
