<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leadgen extends Model
{
    use HasFactory;

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    public function lessons()
    {
        return $this->hasMany(LeadgenLesson::class)->orderBy('display_order');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model){
            $uuid = $model['uuid'];
            unset($model['uuid']);


            if(gettype($model['meta_img']) === 'object'){
                $model['meta_img'] = 'https://laravel-nova.s3.us-east-2.amazonaws.com/'.$model->brand->name.'/Lead-gens/Meta-images/'.$uuid.'-'.$model['meta_img']->getClientOriginalName();
            }

        });

    }
}
