<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;

    protected $with = ["brand", "productType"];

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    public function productType()
    {
        return $this->belongsTo(ProductType::class, 'product_type_id');
    }

    public function features()
    {
        return $this->hasMany(Feature::class)->orderBy('order_number');
    }

    public function specs()
    {
        return $this->hasMany(Spec::class)->orderBy('order_number');
    }

    public function benefits()
    {
        return $this->hasMany(Benefit::class);
    }

    public function sizes()
    {
        return $this->hasManyThrough(Size::class, ProductSize::class, 'product_id', 'id', 'id', 'size_id')
                    ->addSelect(['product_sizes.sold_out', 'product_sizes.id', 'sizes.name', 'sizes.id as sizeId', 'sizes.code'])->orderBy('sizeId');
    }

    public function product_size()
    {
        return $this->hasMany(ProductSize::class);
    }

    public function images()
    {
        return $this->hasMany(Image::class)->orderBy('order_number');
    }

    public function bundles()
    {
        return $this->hasManyThrough( Product::class,Bundle::class, 'bundle_id', 'id', 'id', 'product_id')->select(['products.name', 'bundles.id', 'bundles.product_id as bundle_product_id', 'products.thumbnail', 'products.bundle_lifetime_access', 'products.bundle_free_shipping', 'products.price', 'products.free_bonus', 'products.short_desc'])->orderBy('order_number');
    }

    public function sizeChart()
    {
        return $this->belongsTo(SizeChart::class, 'size_chart_id');
    }

    protected function slug(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => str_replace( array('Drumeo-', 'Pianote-', 'Guitareo-', 'Singeo-'), '', $value ),
        );
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model){
            $uuid = $model['uuid'];
            unset($model['uuid']);

            $brandId = $model['brand_id'];
            $brand = '';


            if($brandId === 1) {
                $brand = 'Drumeo';
            }
            elseif($brandId === 2){
                $brand = 'Pianote';
            }
            elseif($brandId === 3){
                $brand = 'Guitareo';
            }
            elseif($brandId === 4){
                $brand = 'Singeo';
            }

            $model['slug'] = $model->brand->name.'-'.$model['slug'];

            if(gettype($model['meta_img']) === 'object'){
                $model['meta_img'] = $brand.'/'.$uuid.'-'.$model['meta_img']->getClientOriginalName();
            }

            if(gettype($model['thumbnail']) === 'object'){
                $model['thumbnail'] = $brand.'/'.$uuid.'-'.$model['thumbnail']->getClientOriginalName();
            }

            if(gettype($model['thumbnail_logo']) === 'object'){
                $model['thumbnail_logo'] = $brand.'/'.$uuid.'-'.$model['thumbnail_logo']->getClientOriginalName();
            }

            if(gettype($model['page_logo']) === 'object'){
                $model['page_logo'] = $brand.'/'.$uuid.'-'.$model['page_logo']->getClientOriginalName();
            }

            if(gettype($model['product_img']) === 'object'){
                $model['product_img'] = $brand.'/'.$uuid.'-'.$model['product_img']->getClientOriginalName();
            }
        });

    }

    public function delete()
    {
        Feature::where('product_id', '=', $this->id)->delete();
        ProductSize::where('product_id', '=', $this->id)->delete();
        Spec::where('product_id', '=', $this->id)->delete();

        $imgs = Image::where('product_id', '=', $this->id)->get();

        foreach($imgs as $img){
            Storage::disk('nova_s3')->delete($img->path);
        }

        Image::where('product_id', '=', $this->id)->delete();

        Bundle::where('bundle_id', '=', $this->id)->delete();

        Product::where('id', '=', $this->id)->delete();
    }

    protected $guarded = [
        'id'
    ];
}
