<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Modules\Content\Models\Content
 *
 * @property integer $id
 * @property integer $brand_id
 * @property string $title
 * @property string $subtitle
 * @property string $description
 * @property string $cta_text
 * @property string $cta_url
 * @property string $img
 * @property integer $display_order
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $start_date
 * @property Carbon $end_date
 * @property integer $visible
 * @property integer $is_featured
 * @property integer $product_id
 * @property integer $challenge_id
 * @property string $product_url
 * @property string $endpoint
 * @property string $video_src
 * @property string $primary_cta_text
 * @property string $primary_cta_text_alt
 * @property string $primary_cta_url
 * @property string $primary_cta_url_alt
 * @property string $secondary_cta_text
 * @property string $secondary_cta_url
 */
class TrialSection extends Model
{
    use HasFactory;

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }

    protected $guarded = [
        'id'
    ];

    protected $casts = [
        'start_date' => 'datetime',
        'end_date' => 'datetime',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function ($model) {
            $uuid = $model['uuid'];
            unset($model['uuid']);

            if (gettype($model['desktop_img']) === 'object') {
                $model['desktop_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/' . $model->brand->name . '/learning-paths/' . $uuid . '-' . str_replace(' ', '+', $model['desktop_img']->getClientOriginalName());
            }

            if (gettype($model['tablet_img']) === 'object') {
                $model['tablet_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/' . $model->brand->name . '/learning-paths/' . $uuid . '-' . str_replace(' ', '+', $model['tablet_img']->getClientOriginalName());
            }

            if (gettype($model['mobile_img']) === 'object') {
                $model['mobile_img'] = 'https://d1fyshwdvi6fth.cloudfront.net/' . $model->brand->name . '/learning-paths/' . $uuid . '-' .str_replace(' ', '+', $model['mobile_img']->getClientOriginalName());
            }
        });
    }
}
