<?php

$bonuses = [
    [
        'image' => 'https://d1fyshwdvi6fth.cloudfront.net/Pianote/Bundle-images/fb81d171-6ee7-46bb-bd5e-b29de32766c5-NPPSH-card.jpg',
        'title' => 'New Piano Players Start Here',
        'description' => 'New to the piano? Start here! This play-along course is your first 30 days on the piano. You don’t need any previous experience or theory knowledge. Over 30 days, you’ll play along with your teacher for just 10 minutes a day! You’ll be amazing at what a little bit of consistent practice will do.',
        'price' => floatval($productPrices['new-piano-players-start-here']->price),
    ],
    [
        'image' => 'https://d1fyshwdvi6fth.cloudfront.net/Pianote/Bundle-images/2bae4048-37d2-4fe4-a195-431de3f7f822-easy-chords-card.jpg',
        'title' => 'Easy Chords',
        'description' => 'Chords are the foundation of all music. But they can be tricky to understand, let alone practice. Easy Chords solves that problem. Over 30 days, you’ll play with a teacher and unlock the beauty and power of piano chord progressions. You’ll be able to play hundreds of songs after taking this course. And best of all? It only takes 10 minutes a day.',
        'price' => floatval($productPrices['easy-chords']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/shop/card-thumbs/headphones-cart.jpg',
        'title' => 'Pianote Headphones',
        'description' => 'Hear your piano the way it was meant to sound.',
        'price' => floatval($productPrices['pianote-headphones']->price),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/may/Pianote_Planner_Card.jpg',
        'title' => 'Practice Planner',
        'description' => 'Always know exactly what to practice.',
        'price' => floatval($productPrices['pianote-practice-planner']->price),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/2022/bonus-chords-scales.jpg',
        'title' => 'Chords & <br>Scales Book',
        'description' => 'Your encyclopedia of piano chords & scales.',
        'price' => floatval($productPrices['piano-chords-and-scales-guide']->price),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/may/Piano_Chords_Card.jpg',
        'title' => 'Chords Poster',
        'description' => 'Hang these piano chords in your practice space.',
        'price' => floatval($productPrices['poster-chords']->price),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/may/Piano_Scales_Card.jpg',
        'title' => 'Scales Poster',
        'description' => 'All the major and minor piano scales in one poster.',
        'price' => floatval($productPrices['poster-scales']->price),
        'shipping' => true,
    ],

    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/chords-poster.jpg',
        'title' => 'Chords Poster',
        'description' => 'Play every major and minor chord.',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/chord-formulas-poster.jpg',
        'title' => 'Chord Formulas Poster',
        'description' => 'Play any chord. On any key. ',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/circle-of-fifths-poster.jpg',
        'title' => 'Circle Of 5ths Poster',
        'description' => 'The essential piece of music theory.',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/key-to-sight-reading-poster.jpg',
        'title' => 'Keys To Sight Reading Poster',
        'description' => 'Link the notes on the page to your keys.',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/dynamics-poster.jpg',
        'title' => 'Dynamics Poster',
        'description' => 'Don’t learn Italian. Just look at this poster.',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/september/scales-poster.jpg',
        'title' => 'Scales Poster',
        'description' => 'All the major and minor scales in one place.',
        'price' => floatval(($productPrices['music-theory-posters']->price / 6)),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/november/bonuses/christmas-songbook-card.jpg',
        'title' => 'Christmas Songbook Digital',
        'description' => 'Play Your Favorite Christmas Songs on the Piano.',
        'price' => floatval($productPrices['christmas-song-book-digital']->price),
        'shipping' => true,
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/october/power_of_chords_card.jpg',
        'title' => 'The Power of Chords',
        'description' => 'Play the music you love using the power of chords.',
        'price' => floatval($productPrices['the-power-of-chords']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/november/bonuses/TBGTCP.jpg',
        'title' => 'Classical Piano',
        'description' => 'Pieces you can actually play, with lessons that are actually fun.',
        'price' => floatval($productPrices['classical-piano']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/black-friday/unlimited/piano-technique-made-easy.jpg',
        'title' => 'Piano Technique<br> Made Easy',
        'description' => 'Your ultimate guide to learning the piano. Learn EVERY scale, chord, arpeggio, and key signature.',
        'price' => floatval($productPrices['piano-technique-made-easy']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/black-friday/unlimited/piano-riffs-and-fills.jpg',
        'title' => 'Piano Riffs<br> & Fills',
        'description' => 'Learn the secrets and tips to play fills that sound complicated and advanced, but are simple to learn.',
        'price' => floatval($productPrices['piano-riffs-and-fills']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/black-friday/unlimited/de-stupefy-your-left-hand.jpg',
        'title' => 'De-Stupefy Your<br> Left Hand',
        'description' => 'Most piano players find their left-hand is weaker. Fix those weaknesses and “de-stupefy” that left hand.',
        'price' => floatval($productPrices['destupefy-your-left-hand']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/black-friday/unlimited/worship-piano.jpg',
        'title' => 'Worship Piano',
        'description' => 'Learn hundreds of worship songs and get the skills to start playing in a worship band.',
        'price' => floatval($productPrices['worship-piano']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/black-friday/faster-fingers.jpg',
        'title' => 'Faster Fingers',
        'description' => 'Boost your speed and confidence with this guided practice course.',
        'price' => floatval($productPrices['faster-fingers']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/november/bonuses/TBGTPBP.jpg',
        'title' => 'Play Beautiful Piano',
        'description' => 'Start playing beautiful music from your very 1st lesson.',
        'price' => floatval($productPrices['play-beautiful-piano']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/november/bonuses/improv-musical-freedom.jpg',
        'title' => 'Improvisation & Musical Freedom',
        'description' => 'Learn to improvise from one of the best piano players in the world, Jesús Molina',
        'price' => floatval($productPrices['jesus-molina-improvisation-and-musical-freedom-pack']->price),
    ],
    [
        'image' => 'https://d2vyvo0tyx8ig5.cloudfront.net/sales/promos/november/bonuses/classical-piano-book.jpg',
        'title' => 'Classical <br>Book',
        'description' => '92 pages full of beautiful pieces by famous classical composers that you can actually play!',
        'price' => floatval($productPrices['classical-book']->price),
    ],
    [
        'image' => 'https://d1fyshwdvi6fth.cloudfront.net/Pianote/Thumbnails/5307c3c2-d687-44d9-8da5-e8be784f8c86-classical-piano-pieces-shop-card.jpg',
        'description' => 'Timeless classics you’ll want to play over and over again. Presented in original and simplified arrangements.',
        'price' => 49,
        'shipping' => true,
    ],
];
