name: Automated Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: "Musora Web Platform"
  APP_ENV: local
  APP_KEY: base64:wvzEaUzwx/M/xIlIiZ9p1P6kWmC6cHsIqoQzFhHIWps=
  APP_DEBUG: false
  DEBUGBAR_ENABLED: false
  APP_URL: http://localhost
  LOG_LEVEL: warning
  RAILTRACKER_ENABLED: false

jobs:
  laravel-tests:

    runs-on:
      group: Default Larger Runners
      labels: ubuntu-latest-16-cores

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: musora_web_platform_automated_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Create .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -u"root" -p"root" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      - name: Execute tests via artisan command
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: musora_web_platform_automated_tests
          DB_MUSORA_LARAVEL_MYSQL_WRITE_HOST: 127.0.0.1
          DB_MUSORA_LARAVEL_MYSQL_READ_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test --parallel --recreate-databases --coverage-clover=clover.xml

      - name: Generate coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./clover.xml
          name: codecov-umbrella
          fail_ci_if_error: true
