name: Automated Testing

on:
  push:
    branches: [ "fix-test-robwillems" ]
  pull_request:
    branches: [ "fix-test-robwillems" ]

env:
  APP_NAME: "Musora Web Platform"
  APP_ENV: local
  APP_KEY: base64:wvzEaUzwx/M/xIlIiZ9p1P6kWmC6cHsIqoQzFhHIWps=
  APP_DEBUG: false
  DEBUGBAR_ENABLED: false
  APP_URL: http://localhost
  LOG_LEVEL: warning
  RAILTRACKER_ENABLED: false
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: actions/checkout@v3
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      - name: Create .env
        run: php -r "file_exists('.env') || file_put_contents('.env', '');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute Unit Tests via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --testsuite Unit
      - name: Execute Feature tests via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --testsuite Feature --testdox
